// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ClientFacingBodyFatTimeseries } from "../../../types/ClientFacingBodyFatTimeseries.js";

export const Response: core.serialization.Schema<
    serializers.vitals.bodyFat.Response.Raw,
    Junction.ClientFacingBodyFatTimeseries[]
> = core.serialization.list(ClientFacingBodyFatTimeseries);

export declare namespace Response {
    export type Raw = ClientFacingBodyFatTimeseries.Raw[];
}
