// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "user_id",
 *         provider: "provider",
 *         startDate: "start_date",
 *         endDate: "end_date"
 *     }
 */
export interface GetMenstrualCycleRequest {
    userId: string;
    /** Provider oura/strava etc */
    provider?: string | null;
    /** Start date in YYYY-MM-DD */
    startDate: string;
    /** End date (inclusive) in YYYY-MM-DD */
    endDate?: string | null;
}
