// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { PayorCodeExternalProvider } from "../../../../types/PayorCodeExternalProvider.js";

export const PayorSearchRequest: core.serialization.Schema<
    serializers.PayorSearchRequest.Raw,
    Junction.PayorSearchRequest
> = core.serialization.object({
    insuranceName: core.serialization.property("insurance_name", core.serialization.string().optionalNullable()),
    provider: PayorCodeExternalProvider.optionalNullable(),
    providerId: core.serialization.property("provider_id", core.serialization.string().optionalNullable()),
});

export declare namespace PayorSearchRequest {
    export interface Raw {
        insurance_name?: (string | null | undefined) | null;
        provider?: (PayorCodeExternalProvider.Raw | null | undefined) | null;
        provider_id?: (string | null | undefined) | null;
    }
}
