// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { Providers } from "../../../../types/Providers.js";

export const LinkTokenExchange: core.serialization.Schema<
    serializers.LinkTokenExchange.Raw,
    Junction.LinkTokenExchange
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    provider: Providers.optionalNullable(),
    redirectUrl: core.serialization.property("redirect_url", core.serialization.string().optionalNullable()),
    filterOnProviders: core.serialization.property(
        "filter_on_providers",
        core.serialization.list(Providers).optionalNullable(),
    ),
    onError: core.serialization.property("on_error", core.serialization.stringLiteral("redirect").optionalNullable()),
    onClose: core.serialization.property("on_close", core.serialization.stringLiteral("redirect").optionalNullable()),
});

export declare namespace LinkTokenExchange {
    export interface Raw {
        user_id: string;
        provider?: (Providers.Raw | null | undefined) | null;
        redirect_url?: (string | null | undefined) | null;
        filter_on_providers?: (Providers.Raw[] | null | undefined) | null;
        on_error?: ("redirect" | null | undefined) | null;
        on_close?: ("redirect" | null | undefined) | null;
    }
}
