// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: [fs.createReadStream("/path/to/your/file")],
 *         userId: "user_id"
 *     }
 */
export interface CreateLabReportParserJobBody {
    file: core.file.Uploadable[];
    userId: string;
    needsHumanReview?: boolean;
}
