// This file was auto-generated by Fern from our API Definition.

export const GetLabTestsRequestOrderDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetLabTestsRequestOrderDirection =
    (typeof GetLabTestsRequestOrderDirection)[keyof typeof GetLabTestsRequestOrderDirection];
