// This file was auto-generated by Fern from our API Definition.

export const GetOrdersLabTestsRequestOrderDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetOrdersLabTestsRequestOrderDirection =
    (typeof GetOrdersLabTestsRequestOrderDirection)[keyof typeof GetOrdersLabTestsRequestOrderDirection];
