// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { Consent } from "../../../../types/Consent.js";
import { HealthInsuranceCreateRequest } from "../../../../types/HealthInsuranceCreateRequest.js";
import { PatientAddressWithValidation } from "../../../../types/PatientAddressWithValidation.js";
import { PatientDetailsWithValidation } from "../../../../types/PatientDetailsWithValidation.js";
import { PhysicianCreateRequestBase } from "../../../../types/PhysicianCreateRequestBase.js";

export const RegisterTestkitRequest: core.serialization.Schema<
    serializers.RegisterTestkitRequest.Raw,
    Junction.RegisterTestkitRequest
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string().optionalNullable()),
    sampleId: core.serialization.property("sample_id", core.serialization.string()),
    patientDetails: core.serialization.property("patient_details", PatientDetailsWithValidation),
    patientAddress: core.serialization.property("patient_address", PatientAddressWithValidation),
    physician: PhysicianCreateRequestBase.optionalNullable(),
    healthInsurance: core.serialization.property("health_insurance", HealthInsuranceCreateRequest.optionalNullable()),
    consents: core.serialization.list(Consent).optional(),
});

export declare namespace RegisterTestkitRequest {
    export interface Raw {
        user_id?: (string | null | undefined) | null;
        sample_id: string;
        patient_details: PatientDetailsWithValidation.Raw;
        patient_address: PatientAddressWithValidation.Raw;
        physician?: (PhysicianCreateRequestBase.Raw | null | undefined) | null;
        health_insurance?: (HealthInsuranceCreateRequest.Raw | null | undefined) | null;
        consents?: Consent.Raw[] | null;
    }
}
