// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: "order_id",
 *         cancellationReasonId: "cancellation_reason_id"
 *     }
 */
export interface ApiApiV1EndpointsVitalApiLabTestingOrdersHelpersAppointmentCancelRequest {
    /** Your Order ID. */
    orderId: string;
    cancellationReasonId: string;
    notes?: string | null;
}
