// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: "order_id"
 *     }
 */
export interface CancelOrderLabTestsRequest {
    /** Your Order ID. */
    orderId: string;
}
