// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         rawResultId: "raw_result_id"
 *     }
 */
export interface CreateUnmatchedResultUpdateBody {
    rawResultId: string;
    note?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    status?: Junction.UnmatchedResultUpdateStatus | null;
}
