// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         idempotencyKey: "X-Idempotency-Key",
 *         "case": "match_completed",
 *         orderSource: "managed"
 *     }
 */
export interface CreateUnmatchedResultTestBody {
    idempotencyKey: string;
    /** ℹ️ This enum is non-exhaustive. */
    case: Junction.UnmatchedResultTestCase;
    /** ℹ️ This enum is non-exhaustive. */
    orderSource: Junction.UnmatchedResultTestOrderSource;
    orders?: Record<string, string | null> | null;
    /** ℹ️ This enum is non-exhaustive. */
    resultStatus?: Junction.ResultStatus;
    /** ℹ️ This enum is non-exhaustive. */
    interpretation?: Junction.Interpretation;
    labTestId?: string | null;
    wrongLabTestId?: string | null;
}
