// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         zipCode: "zip_code",
 *         radius: "10",
 *         lab: "quest",
 *         labs: ["quest"],
 *         labAccountId: "lab_account_id"
 *     }
 */
export interface GetAreaInfoLabTestsRequest {
    /** Zip code of the area to check */
    zipCode: string;
    /** Radius in which to search in miles */
    radius?: Junction.AllowedRadius | null;
    /** Lab to check for PSCs */
    lab?: Junction.ClientFacingLabs | null;
    /** List of labs to check for PSCs */
    labs?: (Junction.ClientFacingLabs | null) | (Junction.ClientFacingLabs | null)[];
    /** Lab Account ID to use for availability checks */
    labAccountId?: string | null;
}
