// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         labTestId: "lab_test_id"
 *     }
 */
export interface GetLabTestCollectionInstructionPdfLabTestsRequest {
    labTestId: string;
}
