// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: "order_id",
 *         collectionDate: new Date("2024-01-15T09:30:00.000Z")
 *     }
 */
export interface GetLabelsPdfLabTestsRequest {
    orderId: string;
    /** Number of labels to generate */
    numberOfLabels?: number | null;
    /** Collection date */
    collectionDate: Date;
}
