// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         providerId: "provider_id",
 *         labId: 1,
 *         labAccountId: "lab_account_id"
 *     }
 */
export interface GetMarkersByLabAndProviderIdLabTestsRequest {
    providerId: string;
    labId: number;
    /** The lab account ID. This lab account is used to determine the availability of markers and lab tests. */
    labAccountId?: string | null;
}
