// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         page: 1,
 *         size: 1,
 *         body: {}
 *     }
 */
export interface GetMarkersForOrderSetLabTestsRequest {
    page?: number | null;
    size?: number | null;
    body: Junction.OrderSetRequest;
}
