// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         orderId: "order_id",
 *         radius: "10",
 *         capabilities: ["stat"]
 *     }
 */
export interface GetOrderPscInfoLabTestsRequest {
    /** Your Order ID. */
    orderId: string;
    /** Radius in which to search in miles */
    radius?: Junction.AllowedRadius | null;
    /** Filter for only locations with certain capabilities */
    capabilities?: (Junction.LabLocationCapability | null) | (Junction.LabLocationCapability | null)[];
}
