// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         startDate: "start_date",
 *         body: {
 *             firstLine: "first_line",
 *             city: "city",
 *             state: "state",
 *             zipCode: "zip_code"
 *         }
 *     }
 */
export interface GetPhlebotomyAppointmentAvailabilityLabTestsRequest {
    /** Start date for appointment availability */
    startDate?: string | null;
    /** At-home phlebotomy appointment address. */
    body: Junction.UsAddress;
}
