// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sourceSandboxLabTestIds: ["source_sandbox_lab_test_ids"]
 *     }
 */
export interface ListPromotionsLabTestsRequest {
    sourceSandboxLabTestIds?: string | string[];
}
