// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         rawResultId: "raw_result_id",
 *         action: "reject"
 *     }
 */
export interface ResolveUnmatchedResultBody {
    rawResultId: string;
    /** ℹ️ This enum is non-exhaustive. */
    action: Junction.UnmatchedResultResolutionAction;
    note?: string | null;
}
