// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         orderId: "order_id",
 *         finalStatus: "received.walk_in_test.ordered",
 *         delay: 1,
 *         body: {}
 *     }
 */
export interface SimulateOrderProcessLabTestsRequest {
    orderId: string;
    finalStatus?: Junction.OrderStatus | null;
    delay?: number | null;
    body?: Junction.SimulationFlags | null;
}
