// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: "order_id"
 *     }
 */
export interface UpdateOrderBody {
    /** Your Order ID. */
    orderId: string;
    /** The date on which the order should be activated (dispatched to the lab). Must be today or a future date. Set to `null` to clear an existing scheduled date and dispatch the order immediately. Note: an order originally created for immediate processing (no `activate_by` at creation time) cannot be rescheduled — only orders that were created with an `activate_by` can have it changed or cleared. */
    activateBy?: string | null;
}
