// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         userId: "user_id",
 *         provider: "oura"
 *     }
 */
export interface DeregisterProviderUserRequest {
    userId: string;
    /** Provider slug. e.g., `oura`, `fitbit`, `garmin`. */
    provider: Junction.Providers;
}
