// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "user_id",
 *         isPrimary: true
 *     }
 */
export interface GetLatestInsuranceUserRequest {
    userId: string;
    isPrimary?: boolean | null;
}
