// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "user_id",
 *         timeout: 1.1
 *     }
 */
export interface RefreshUserRequest {
    userId: string;
    timeout?: number | null;
}
