// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         userId: "user_id",
 *         firstName: "first_name",
 *         lastName: "last_name",
 *         email: "email",
 *         phoneNumber: "phone_number",
 *         gender: "gender",
 *         dob: "dob",
 *         address: {
 *             firstLine: "first_line",
 *             country: "country",
 *             zip: "zip",
 *             city: "city",
 *             state: "state"
 *         }
 *     }
 */
export interface UserInfoCreateRequest {
    userId: string;
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: string;
    gender: string;
    dob: string;
    address: Junction.UserAddress;
    medicalProxy?: Junction.GuarantorDetails | null;
    /** ℹ️ This enum is non-exhaustive. */
    race?: Junction.Race | null;
    /** ℹ️ This enum is non-exhaustive. */
    ethnicity?: Junction.Ethnicity | null;
    /** ℹ️ This enum is non-exhaustive. */
    sexualOrientation?: Junction.SexualOrientation | null;
    /** ℹ️ This enum is non-exhaustive. */
    genderIdentity?: Junction.GenderIdentity | null;
}
