// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "oura"
 *     }
 */
export interface BulkExportConnectionsBody {
    userIds?: string[] | null;
    /** ℹ️ This enum is non-exhaustive. */
    provider: Junction.OAuthProviders;
    nextToken?: string | null;
}
