// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "whoop",
 *         mfaCode: "mfa_code"
 *     }
 */
export interface CompletePasswordProviderMfaBody {
    provider: Junction.PasswordProviders;
    vitalLinkToken?: string | null;
    mfaCode: string;
}
