// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         provider: "freestyle_libre",
 *         email: "email"
 *     }
 */
export interface EmailProviderAuthLink {
    provider: Junction.EmailProviders;
    vitalLinkToken?: string | null;
    email: string;
    /** ℹ️ This enum is non-exhaustive. */
    emailProviderAuthLinkProvider?: Junction.Providers | null;
    /** ℹ️ This enum is non-exhaustive. */
    region?: Junction.Region;
}
