// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         oauthProvider: "oura"
 *     }
 */
export interface GenerateOauthLinkLinkRequest {
    oauthProvider: Junction.OAuthProviders;
    vitalLinkToken?: string | null;
}
