// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         insuranceName: "insurance_name",
 *         provider: "change_healthcare",
 *         providerPayorId: "provider_payor_id"
 *     }
 */
export interface SearchGetPayorInfoInsuranceRequest {
    insuranceName?: string | null;
    provider?: Junction.PayorCodeExternalProvider | null;
    providerPayorId?: string | null;
}
