// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ClientFacingDiagnosisInformation } from "../../../types/ClientFacingDiagnosisInformation.js";

export const Response: core.serialization.Schema<
    serializers.insurance.searchDiagnosis.Response.Raw,
    Junction.ClientFacingDiagnosisInformation[]
> = core.serialization.list(ClientFacingDiagnosisInformation);

export declare namespace Response {
    export type Raw = ClientFacingDiagnosisInformation.Raw[];
}
