// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export type AggregateFieldExprArg =
    | Junction.McMenstrualFlowFieldExpr
    | Junction.McCervicalMucusFieldExpr
    | Junction.McIntermenstrualBleedingFieldExpr
    | Junction.McContraceptiveFieldExpr
    | Junction.McDetectedDeviationsFieldExpr
    | Junction.McOvulationTestFieldExpr
    | Junction.McHomePregnancyTestFieldExpr
    | Junction.McHomeProgesteroneTestFieldExpr
    | Junction.McSexualActivityFieldExpr
    | Junction.McBasalBodyTemperatureFieldExpr
    | Junction.ElementFieldExpr;
