// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const AggregateFieldExprFunc = {
    Mean: "mean",
    Min: "min",
    Max: "max",
    Sum: "sum",
    Count: "count",
    Median: "median",
    Stddev: "stddev",
    Oldest: "oldest",
    Newest: "newest",
} as const;
export type AggregateFieldExprFunc = (typeof AggregateFieldExprFunc)[keyof typeof AggregateFieldExprFunc];
