// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * Post-aggregation alignment clause for a CQ query.
 *
 * `carry` runs after group_by+aggregate, implicitly materialising missing
 * datetime buckets before filling them. Omitting `.align()` entirely preserves
 * honest-null behaviour; the `carry` field is required when `align` is present.
 */
export interface AlignExpr {
    carry: Junction.AlignExprCarry;
}
