// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface AppointmentAvailabilitySlots {
    slots: Junction.DaySlots[];
    timezone?: string | null;
}
