// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const AppointmentPscLabs = {
    Quest: "quest",
    SonoraQuest: "sonora_quest",
} as const;
export type AppointmentPscLabs = (typeof AppointmentPscLabs)[keyof typeof AppointmentPscLabs];
