// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface BloodPressureTimeseriesExpr {
    timeseries: "blood_pressure";
    /** ℹ️ This enum is non-exhaustive. */
    field: Junction.BloodPressureTimeseriesExprField;
}
