// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * Post-aggregation carry operator: last-observation-carried-forward.
 *
 * For each empty bucket, carries the most recent prior non-empty bucket's
 * aggregate forward. `max_age=None` means no cap (carry indefinitely);
 * when set, enforced >= group_by_period at CQ validation time.
 */
export interface CarryForwardExpr {
    maxAge?: Junction.Period | null;
}
