// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface CheckoutSession {
    checkoutId: string;
    /** ℹ️ This enum is non-exhaustive. */
    status: Junction.CheckoutSessionStatus;
    payBefore: Date;
    paymentResourceId?: string | null;
    orderId?: string | null;
    orderTransactionId?: string | null;
}
