// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface CheckoutQuoteLineItem {
    /** ℹ️ This enum is non-exhaustive. */
    code: Junction.CheckoutQuoteLineItemCode;
    amountMinor: number;
    currency: "USD";
}
