// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * A checkout session collects payment for a quote; once it is paid, the
 * order is created. The checkout session endpoints return this object, and
 * `checkout.session.*` webhooks carry it as `data`.
 */
export interface CheckoutSession {
    checkoutSessionId: string;
    /** ℹ️ This enum is non-exhaustive. */
    status: Junction.CheckoutSessionStatus;
    payBefore: Date;
    /** ID of the Stripe Checkout Session (`cs_...`) or PaymentIntent (`pi_...`) collecting payment. `null` until the payment resource is created. */
    paymentResourceId?: string | null;
    orderId?: string | null;
    orderTransactionId?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    appointmentHoldStatus?: Junction.CheckoutAppointmentHoldStatus | null;
    appointmentId?: string | null;
    /** Stripe-hosted payment page URL, for the `checkout_session` payment method. Returned only by the create, get and confirm endpoints while `status` is `unpaid`; always `null` in webhooks. */
    paymentResourceUrl?: string | null;
    /** Client secret for confirming the Stripe PaymentIntent with Stripe.js, for the `payment_intent` payment method. Returned only by the create, get and confirm endpoints while `status` is `unpaid`; always `null` in webhooks. */
    paymentResourceClientSecret?: string | null;
}
