// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const CheckoutQuoteLineItemCode = {
    LabTestFee: "lab_test_fee",
    DrawFee: "draw_fee",
} as const;
export type CheckoutQuoteLineItemCode = (typeof CheckoutQuoteLineItemCode)[keyof typeof CheckoutQuoteLineItemCode];
