// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingElectrocardiogram {
    id: string;
    sessionStart: Date;
    sessionEnd: Date;
    voltageSampleCount: number;
    heartRateMean?: number | null;
    samplingFrequencyHz?: number | null;
    /** ℹ️ This enum is non-exhaustive. */
    classification?: Junction.ClientFacingElectrocardiogramClassification | null;
    /** ℹ️ This enum is non-exhaustive. */
    inconclusiveCause?: Junction.ClientFacingElectrocardiogramInconclusiveCause | null;
    algorithmVersion?: string | null;
    timeZone?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    sourceProvider: Junction.ClientFacingElectrocardiogramSourceProvider;
    /** ℹ️ This enum is non-exhaustive. */
    sourceType: Junction.ClientFacingElectrocardiogramSourceType;
    sourceAppId?: string | null;
    sourceDeviceModel?: string | null;
    sourceDeviceId?: string | null;
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    source: Junction.ClientFacingSource;
}
