// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingConnectionErrorDetails {
    /** ℹ️ This enum is non-exhaustive. */
    errorType: Junction.ClientFacingConnectionErrorDetailsErrorType;
    errorMessage: string;
    erroredAt: Date;
}
