// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingLabReportParsingJobUpdatedEvent {
    eventType: "lab_report.parsing_job.updated";
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.ParsingJob;
}
