// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingBloodPressureChanged {
    eventType: Junction.ClientFacingBloodPressureChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.GroupedBloodPressure;
}
