// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingCarbohydratesHistoricalPullCompleted {
    eventType: "historical.data.carbohydrates.created";
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.HistoricalPullCompleted;
}
