// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingLabAccount {
    id: string;
    /** ℹ️ This enum is non-exhaustive. */
    lab: Junction.Labs;
    orgId?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    status: Junction.LabAccountStatus;
    /** ℹ️ This enum is non-exhaustive. */
    delegatedFlow: Junction.LabAccountDelegatedFlow;
    providerAccountId: string;
    accountName?: string | null;
    defaultClinicalNotes?: string | null;
    businessUnits?: string[] | null;
    allowedBilling: Record<string, Junction.UsState[]>;
    teamIdAllowlist: string[];
}
