// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingActivityChanged {
    eventType: Junction.ClientFacingActivityChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.ClientFacingActivity;
}
