// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingProfileChanged {
    eventType: Junction.ClientFacingProfileChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.ClientFacingProfile;
}
