// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingProviderDetailed {
    /** Name of source of information */
    name: string;
    /** Slug for designated source */
    slug: string;
    /** Description of source of information */
    description: string;
    /** URL for source logo */
    logo?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    authType?: Junction.SourceAuthType | null;
    supportedResources?: Junction.ClientFacingResource[];
}
