// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingLabLocation {
    metadata: Junction.LabLocationMetadata;
    distance: number;
    siteCode: string;
    supportedBillTypes: Junction.Billing[];
    location: Junction.LngLat;
    capabilities: Junction.LabLocationCapability[];
}
