// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingWorkout {
    id: string;
    /** User id returned by vital create user request. This id should be stored in your database against the user and used for all interactions with the vital api. */
    userId: string;
    /** Title given for the workout */
    title?: string | null;
    /** Timezone offset from UTC as seconds. For example, EEST (Eastern European Summer Time, +3h) is 10800. PST (Pacific Standard Time, -8h) is -28800::seconds */
    timezoneOffset?: number | null;
    /** Average heart rate during workout::bpm */
    averageHr?: number | null;
    /** Max heart rate during workout::bpm */
    maxHr?: number | null;
    /** Distance travelled during workout::meters */
    distance?: number | null;
    /** Date of the workout summary in the YYYY-mm-dd format. This generally matches the workout start date. */
    calendarDate: string;
    /** Start time of the workout::time */
    timeStart: Date;
    /** End time of the workout::time */
    timeEnd: Date;
    /** Calories burned during the workout::kCal */
    calories?: number | null;
    /** Sport's name */
    sport?: Junction.ClientFacingSport;
    /** Time in seconds spent in different heart rate zones <50%, 50-60%, 60-70%, 70-80%, 80-90%, 90%+. Due to rounding errors, it's possible that summing all values is different than the total time of the workout. Not available for all providers::seconds */
    hrZones?: number[] | null;
    /** Time spent active during the workout::seconds */
    movingTime?: number | null;
    /** Elevation gain during the workout::meters */
    totalElevationGain?: number | null;
    /** Highest point of elevation::meters */
    elevHigh?: number | null;
    /** Lowest point of elevation::meters */
    elevLow?: number | null;
    /** Average speed during workout in m/s::meters/sec */
    averageSpeed?: number | null;
    /** Max speed during workout in m/s::meters/sec */
    maxSpeed?: number | null;
    /** Average watts burned during exercise::watts */
    averageWatts?: number | null;
    /** Watts burned during exercise::watts */
    deviceWatts?: number | null;
    /** Max watts burned during exercise::watts */
    maxWatts?: number | null;
    /** Weighted average watts burned during exercise::watts */
    weightedAverageWatts?: number | null;
    /** Number of steps accumulated during this workout::count */
    steps?: number | null;
    /** Map of the workout */
    map?: Junction.ClientFacingWorkoutMap | null;
    /** Provider ID given for that specific workout */
    providerId: string;
    /** Source the data has come from. */
    source: Junction.ClientFacingSource;
    createdAt: Date;
    updatedAt: Date;
}
