// This file was auto-generated by Fern from our API Definition.

export interface ClientFacingHeartRate {
    /** Average heart rate::bpm */
    avgBpm?: number | null;
    /** Minimum heart rate::bpm */
    minBpm?: number | null;
    /** Maximum heart rate::bpm */
    maxBpm?: number | null;
    /** Resting heart rate::bpm */
    restingBpm?: number | null;
    avgWalkingBpm?: number | null;
}
