// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * Order transaction info.
 */
export interface ClientFacingOrderTransaction {
    id: string;
    /** ℹ️ This enum is non-exhaustive. */
    status: Junction.OrderTransactionStatus;
    orders: Junction.ClientFacingOrderInTransaction[];
}
