// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingSleepBreathingDisturbanceChanged {
    eventType: Junction.ClientFacingSleepBreathingDisturbanceChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.GroupedSleepBreathingDisturbance;
}
