// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingStandHourChanged {
    eventType: Junction.ClientFacingStandHourChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.GroupedStandHour;
}
