// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingCaloriesActiveChanged {
    eventType: Junction.ClientFacingCaloriesActiveChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.GroupedCaloriesActive;
}
