// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingStressLevelChanged {
    eventType: Junction.ClientFacingStressLevelChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.GroupedStressLevel;
}
