// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingInsulinInjectionSample {
    /** Deprecated */
    id?: number | null;
    /** Time zone UTC offset in seconds. Positive offset indicates east of UTC; negative offset indicates west of UTC; and null indicates the time zone information is unavailable at source. */
    timezoneOffset?: number | null;
    /** The insulin formulation type. ℹ️ This enum is non-exhaustive. */
    type: Junction.ClientFacingInsulinInjectionSampleType;
    unit: "unit";
    /** Depracated. The start time (inclusive) of the interval. */
    timestamp: Date;
    /** The start time (inclusive) of the interval. */
    start: Date;
    /** The end time (exclusive) of the interval. */
    end: Date;
    /** The recorded value for the interval. */
    value: number;
    /** How the insulin was delivered. ℹ️ This enum is non-exhaustive. */
    deliveryMode?: Junction.ClientFacingInsulinInjectionSampleDeliveryMode | null;
    /** For bolus deliveries, whether the dose was standard or extended. ℹ️ This enum is non-exhaustive. */
    deliveryForm?: Junction.ClientFacingInsulinInjectionSampleDeliveryForm | null;
    /** For bolus deliveries, what the bolus was intended for. ℹ️ This enum is non-exhaustive. */
    bolusPurpose?: Junction.ClientFacingInsulinInjectionSampleBolusPurpose | null;
}
