// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingContinuousQueryResultTableChanged {
    eventType: "continuous_query.result_table.changed";
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.ContinuousQueryResultTableChanges[];
}
