// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingCheckoutQuoteCreated {
    eventType: "checkout.quote.created";
    teamId: string;
    data: Junction.CheckoutQuote;
}
