// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingMatchReviewChanged {
    eventType: "labtest.match_review.created";
    teamId: string;
    data: Junction.MatchReviewWebhookPayload;
}
