// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * [Deprecated] GET /v2/team is in the process of being removed.
 * Neither customers nor Dashboard should retrieve team settings and metadata directly.
 *
 * All must migrate to the Team endpoints of the Org Management API.
 */
export interface ClientFacingTeam {
    id: string;
    orgId: string;
    name: string;
    svixAppId?: string | null;
    clientId?: string | null;
    clientSecret?: string | null;
    airtableApiKey?: string | null;
    airtableBaseId?: string | null;
    webhookSecret?: string | null;
    apiKey?: string | null;
    apiKeys?: Junction.ClientFacingApiKey[] | null;
    configuration?: Junction.TeamConfig | null;
    testkitsTextsEnabled: boolean;
    labTestsPatientCommunicationEnabled: boolean;
    labTestsPatientSmsCommunicationEnabled: boolean;
    labTestsPatientEmailCommunicationEnabled: boolean;
    logoUrl?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    delegatedFlow: Junction.DelegatedFlowType;
    criticalResultNotificationEmail?: string | null;
}
