// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingWheelchairPushChanged {
    eventType: Junction.ClientFacingWheelchairPushChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.GroupedWheelchairPush;
}
