// This file was auto-generated by Fern from our API Definition.

export const ClientFacingInsulinInjectionSampleDeliveryForm = {
    Standard: "standard",
    Extended: "extended",
} as const;
export type ClientFacingInsulinInjectionSampleDeliveryForm =
    (typeof ClientFacingInsulinInjectionSampleDeliveryForm)[keyof typeof ClientFacingInsulinInjectionSampleDeliveryForm];
