// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingWorkoutDurationChanged {
    eventType: Junction.ClientFacingWorkoutDurationChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.GroupedWorkoutDuration;
}
