// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingCheckoutSessionUpdated {
    eventType: "checkout.session.updated";
    teamId: string;
    data: Junction.CheckoutSession;
}
