// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ClientFacingLeanBodyMassChanged {
    eventType: Junction.ClientFacingLeanBodyMassChangedEventType;
    userId: string;
    clientUserId: string;
    teamId: string;
    data: Junction.GroupedLeanBodyMass;
}
