// This file was auto-generated by Fern from our API Definition.

export interface ClinicalInformation {
    fasting?: boolean;
    notes?: string | null;
    information?: string | null;
    totalVolume?: string | null;
}
