// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const CollectionInferenceSource = {
    LabArrival: "lab_arrival",
    LabAccessioning: "lab_accessioning",
    ScheduledAppointment: "scheduled_appointment",
    DispatchDate: "dispatch_date",
} as const;
export type CollectionInferenceSource = (typeof CollectionInferenceSource)[keyof typeof CollectionInferenceSource];
