// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ComponentPricingConditions {
    usState?: Junction.UsStatePricingCondition | null;
    reflex?: Junction.ReflexPricingCondition | null;
    criticalCare?: Junction.CriticalCarePricingCondition | null;
}
