// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface DatePartExpr {
    arg: Junction.DatePartExprArg;
    /** ℹ️ This enum is non-exhaustive. */
    datePart: Junction.DatePartExprDatePart;
}
