// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface DaySlots {
    location?: Junction.AppointmentLocation | null;
    date: string;
    slots: Junction.TimeSlot[];
}
