// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const EtaUpdateSource = {
    Lab: "lab",
    Junction: "junction",
    Patient: "patient",
} as const;
export type EtaUpdateSource = (typeof EtaUpdateSource)[keyof typeof EtaUpdateSource];
