// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * Aggregated per-panel pricing, keyed by lab test ID.
 */
export interface GetLabTestPricingResponse {
    currency?: "USD";
    data: Record<string, Junction.LabTestPanelPricing>;
}
