// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface GetOrderTransactionResponse {
    id: string;
    teamId: string;
    /** ℹ️ This enum is non-exhaustive. */
    status: Junction.OrderTransactionStatus;
    orders?: Junction.OrderSummary[];
}
