// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface GroupedInsulinInjection {
    source: Junction.ClientFacingSource;
    data: Junction.ClientFacingInsulinInjectionSample[];
}
