// This file was auto-generated by Fern from our API Definition.

/**
 * Describes which parts of the lab testing flow are delegated to the customer.
 *
 * - ORDER_DELEGATED: Ordering using client's physicians, critical result follow up via Junction
 * - RESULT_DELEGATED: Ordering using Junction's Physician Network, critical results handled by client
 * - FULLY_DELEGATED: Order and critical results handled by client
 * - NOT_DELEGATED: Junction handles both ordering and results ℹ️ This enum is non-exhaustive.
 */
export const LabAccountDelegatedFlow = {
    OrderDelegated: "order_delegated",
    ResultDelegated: "result_delegated",
    FullyDelegated: "fully_delegated",
    NotDelegated: "not_delegated",
} as const;
export type LabAccountDelegatedFlow = (typeof LabAccountDelegatedFlow)[keyof typeof LabAccountDelegatedFlow];
