// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface LabReportResult {
    testName: string;
    value: string;
    /** ℹ️ This enum is non-exhaustive. */
    sampleType?: Junction.LabReportResultSampleType;
    /** ℹ️ This enum is non-exhaustive. */
    measurementKind?: Junction.LabReportResultMeasurementKind;
    /** ℹ️ This enum is non-exhaustive. */
    type?: Junction.LabReportResultType | null;
    units?: string | null;
    maxReferenceRange?: number | null;
    minReferenceRange?: number | null;
    sourcePanelName?: string | null;
    loincMatches?: Junction.LoincMatch[] | null;
    /** ℹ️ This enum is non-exhaustive. */
    loincMatchStatus?: Junction.LabReportResultLoincMatchStatus | null;
    /** ℹ️ This enum is non-exhaustive. */
    interpretation?: Junction.Interpretation | null;
    isAboveMaxRange?: boolean | null;
    isBelowMinRange?: boolean | null;
}
