// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface LabTestResourcesResponse {
    data: Junction.ClientFacingLabTest[];
    /** The cursor for fetching the next page, or `null` to fetch the first page. */
    nextCursor?: string | null;
}
