// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ListUnmatchedResultResponse {
    data?: Junction.UnmatchedResult[];
    nextCursor?: string | null;
    total: number;
}
