// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const MatchDecisionCode = {
    MatchSampleId: "match_sample_id",
    MatchCompleted: "match_completed",
    MatchCancelled: "match_cancelled",
    WrongCollection: "wrong_collection",
    WrongLab: "wrong_lab",
    MultipleDemoMatch: "multiple_demo_match",
    MatchSampleIdMismatchDemo: "match_sample_id_mismatch_demo",
    MatchDemo: "match_demo",
    NoMatch: "no_match",
} as const;
export type MatchDecisionCode = (typeof MatchDecisionCode)[keyof typeof MatchDecisionCode];
