// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const MatchReviewResolutionAction = {
    Accept: "accept",
    Reject: "reject",
    Unsure: "unsure",
} as const;
export type MatchReviewResolutionAction =
    (typeof MatchReviewResolutionAction)[keyof typeof MatchReviewResolutionAction];
