// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface MatchReviewCandidate {
    /** ℹ️ This enum is non-exhaustive. */
    candidateType: Junction.MatchCandidateType;
    orderId?: string | null;
    orderTransactionId?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    lastStatus?: Junction.OrderLowLevelStatus | null;
    /** ℹ️ This enum is non-exhaustive. */
    confidenceLevel: Junction.MatchCandidateConfidenceLevel;
    confidenceScore?: number | null;
    reasons?: Junction.MatchCandidateReasonCode[];
    markerOverlap?: Record<string, unknown> | null;
    statusContext?: Record<string, unknown> | null;
}
