// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const MatchReviewStatusFilter = {
    PendingCustomerReview: "pending_customer_review",
    PendingCustomerReviewInProgress: "pending_customer_review:in_progress",
    PendingOpsReview: "pending_ops_review",
    Resolved: "resolved",
} as const;
export type MatchReviewStatusFilter = (typeof MatchReviewStatusFilter)[keyof typeof MatchReviewStatusFilter];
