// This file was auto-generated by Fern from our API Definition.

export interface MatchReviewPatient {
    firstName?: string | null;
    lastName?: string | null;
    dob?: Date | null;
    gender?: string | null;
}
