// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const MatchCandidateConfidenceLevel = {
    High: "high",
    Medium: "medium",
    Low: "low",
} as const;
export type MatchCandidateConfidenceLevel =
    (typeof MatchCandidateConfidenceLevel)[keyof typeof MatchCandidateConfidenceLevel];
