// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const MatchCandidateReasonCode = {
    SampleIdMatch: "sample_id_match",
    LabAccountMismatch: "lab_account_mismatch",
    MatchedCompletedOrder: "matched_completed_order",
    MatchedCancelledOrder: "matched_cancelled_order",
    InvalidCollectionState: "invalid_collection_state",
    DemographicMismatch: "demographic_mismatch",
    DemographicMatch: "demographic_match",
    PossibleWrongLab: "possible_wrong_lab",
    SameLab: "same_lab",
    SameUser: "same_user",
    MarkerOverlapExact: "marker_overlap_exact",
    MarkerOverlapPartial: "marker_overlap_partial",
    MarkerOverlapNone: "marker_overlap_none",
} as const;
export type MatchCandidateReasonCode = (typeof MatchCandidateReasonCode)[keyof typeof MatchCandidateReasonCode];
