// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const MatchReviewStatus = {
    Matched: "matched",
    PendingCustomerReview: "pending_customer_review",
    PendingOpsReview: "pending_ops_review",
    Resolved: "resolved",
} as const;
export type MatchReviewStatus = (typeof MatchReviewStatus)[keyof typeof MatchReviewStatus];
