// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface McBasalBodyTemperatureFieldExpr {
    fieldFor?: "menstrual_cycle";
    /** ℹ️ This enum is non-exhaustive. */
    basalBodyTemperature: Junction.McBasalBodyTemperatureFieldExprBasalBodyTemperature;
}
