// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const McBasalBodyTemperatureFieldExprBasalBodyTemperature = {
    Date: "date",
    Value: "value",
} as const;
export type McBasalBodyTemperatureFieldExprBasalBodyTemperature =
    (typeof McBasalBodyTemperatureFieldExprBasalBodyTemperature)[keyof typeof McBasalBodyTemperatureFieldExprBasalBodyTemperature];
