// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface McSexualActivityFieldExpr {
    fieldFor?: "menstrual_cycle";
    /** ℹ️ This enum is non-exhaustive. */
    sexualActivity: Junction.McSexualActivityFieldExprSexualActivity;
}
