// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const McSexualActivityFieldExprSexualActivity = {
    Date: "date",
    ProtectionUsed: "protection_used",
} as const;
export type McSexualActivityFieldExprSexualActivity =
    (typeof McSexualActivityFieldExprSexualActivity)[keyof typeof McSexualActivityFieldExprSexualActivity];
