// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const MenstrualCycleColumnExprMenstrualCycle = {
    PeriodStart: "period_start",
    PeriodEnd: "period_end",
    CycleEnd: "cycle_end",
    IsPredicted: "is_predicted",
    MenstrualFlow: "menstrual_flow",
    CervicalMucus: "cervical_mucus",
    IntermenstrualBleeding: "intermenstrual_bleeding",
    Contraceptive: "contraceptive",
    DetectedDeviations: "detected_deviations",
    OvulationTest: "ovulation_test",
    HomePregnancyTest: "home_pregnancy_test",
    HomeProgesteroneTest: "home_progesterone_test",
    SexualActivity: "sexual_activity",
    BasalBodyTemperature: "basal_body_temperature",
    SourceType: "source_type",
    SourceProvider: "source_provider",
    SourceAppId: "source_app_id",
    SourceDeviceId: "source_device_id",
} as const;
export type MenstrualCycleColumnExprMenstrualCycle =
    (typeof MenstrualCycleColumnExprMenstrualCycle)[keyof typeof MenstrualCycleColumnExprMenstrualCycle];
