// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface MissingBiomarkerResult {
    name: string;
    slug: string;
    /** ℹ️ This enum is non-exhaustive. */
    inferredFailureType: Junction.FailureType;
    note?: string | null;
    loinc?: string | null;
    loincSlug?: string | null;
    providerId?: string | null;
    sourceMarkers?: Junction.ParentBiomarkerData[] | null;
}
