// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface NoteTimeseriesExpr {
    timeseries: "note";
    /** ℹ️ This enum is non-exhaustive. */
    field: Junction.NoteTimeseriesExprField;
}
