// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface OrderTrackingUpdate {
    createdAt: Date;
    reason?: string | null;
    revisedEstimate?: Date | null;
    impactedMarkers: Junction.OrderTrackingImpactedMarker[];
    /** ℹ️ This enum is non-exhaustive. */
    source: Junction.EtaUpdateSource;
}
