// This file was auto-generated by Fern from our API Definition.

export interface OrderTrackingResultMarker {
    id?: number | null;
    name: string;
    slug: string;
    providerId?: string | null;
}
