// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface OrderTrackingMarker {
    id: number;
    name: string;
    slug: string;
    providerId?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    status: Junction.OrderMarkerTrackingStatus;
    expectedAt: Junction.OrderTrackingEstimate;
    results: Junction.OrderTrackingResultMarker[];
}
