// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface OrderTrackingImpactedMarker {
    id: number;
    name: string;
    providerId?: string | null;
    estimates: Junction.OrderTrackingEstimate;
}
