// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface PaginatedUsersResponse {
    users: Junction.ClientFacingUser[];
    total: number;
    offset: number;
    limit: number;
}
