// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface PhlebotomyProviderInfo {
    /** ℹ️ This enum is non-exhaustive. */
    name: Junction.AppointmentProvider;
    serviceTypes: Junction.AppointmentServiceType[];
}
