// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * An image of the physician signature for health insurance billing
 */
export type PhysicianCreateRequestSignatureImage = Junction.Jpeg | Junction.Png;
