// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * Amount delta in the smallest denomination of the currency, e.g. cents for USD.
 */
export type PricingModifierMarkerPricingConditionsDeltaAmountMinor = number | Junction.PricingModifierRange;
