// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface PricingModifierComponentPricingConditions {
    /** Amount delta in the smallest denomination of the currency, e.g. cents for USD. */
    deltaAmountMinor: Junction.PricingModifierComponentPricingConditionsDeltaAmountMinor;
    conditions: Junction.ComponentPricingConditions;
    /** Property names present in conditions, including names unknown to a deserializer. */
    keys: string[];
}
