// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ProfileColumnExpr {
    /** ℹ️ This enum is non-exhaustive. */
    profile: Junction.ProfileColumnExprProfile;
}
