// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ProviderConnectionError {
    provider: string;
    userId: string;
    message: string;
    /** ℹ️ This enum is non-exhaustive. */
    errorType: Junction.ProviderConnectionErrorErrorType;
    errorDetails: string;
}
