// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ProviderLinkResponse {
    /** ℹ️ This enum is non-exhaustive. */
    state: Junction.ProviderLinkResponseState;
    /** The redirect URL you supplied when creating the Link Token (via `POST /v2/link/token`). */
    redirectUrl?: string | null;
    /** The Link Error Type. This field is populated only when state is `error`. ℹ️ This enum is non-exhaustive. */
    errorType?: Junction.ProviderLinkResponseErrorType | null;
    /** A developer-readable debug description of the Link Error. This field is populated only when state is `error`. */
    error?: string | null;
    /** The provider MFA request. This field is populated only when state is `pending_provider_mfa`. */
    providerMfa?: Junction.ProviderMfaRequest | null;
    /** ℹ️ This enum is non-exhaustive. */
    provider: Junction.PasswordProviders;
    connected: boolean;
    providerId?: string | null;
}
