// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface PscAreaInfoDetails {
    appointmentWithVital: boolean;
    withinRadius: number;
    radius: string;
    capabilities?: Junction.LabLocationCapability[];
}
