// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface PscInfo {
    labId: number;
    /** ℹ️ This enum is non-exhaustive. */
    slug: Junction.Labs;
    patientServiceCenters: Junction.ClientFacingLabLocation[];
}
