// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface Question {
    id: number;
    required: boolean;
    code: string;
    value: string;
    /** ℹ️ This enum is non-exhaustive. */
    type: Junction.QuestionType;
    sequence: number;
    answers: Junction.Answer[];
    constraint?: string | null;
    default?: string | null;
}
