// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ResourceAvailability {
    /** ℹ️ This enum is non-exhaustive. */
    status: Junction.Availability;
    scopeRequirements?: Junction.ScopeRequirementsGrants | null;
}
