// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const ResultStatus = {
    Final: "final",
    Partial: "partial",
} as const;
export type ResultStatus = (typeof ResultStatus)[keyof typeof ResultStatus];
