// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface ResultMetadata {
    patientFirstName?: string | null;
    patientLastName?: string | null;
    dob?: string | null;
    /** ℹ️ This enum is non-exhaustive. */
    gender?: Junction.ResultMetadataGender;
    labName?: string | null;
    dateReported?: string | null;
    dateCollected?: string | null;
    specimenNumber?: string | null;
}
