// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const ResultMetadataGender = {
    Male: "male",
    Female: "female",
    Other: "other",
} as const;
export type ResultMetadataGender = (typeof ResultMetadataGender)[keyof typeof ResultMetadataGender];
