// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * A subquery that produces a single scalar value per row.
 */
export interface ScalarOutputSubqueryExpr {
    select: Junction.ScalarOutputSubqueryExprSelect;
    from: Junction.ScalarOutputSubqueryExprFrom;
    where?: string | null;
}
