// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface SearchCompendiumResponse {
    /** ℹ️ This enum is non-exhaustive. */
    mode: Junction.SearchMode;
    selectedCanonical?: Junction.CanonicalCandidate | null;
    canonicalCandidates?: Junction.CanonicalCandidate[];
    perLab?: Record<string, Junction.PerLabCandidate[]>;
    related?: Junction.RelatedCandidate[];
}
