// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface SingleUserHistoricalPullResponse {
    userId: string;
    provider: Record<string, Junction.SingleProviderHistoricalPullResponse>;
}
