// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

export interface TemperatureTimeseriesExpr {
    /** ℹ️ This enum is non-exhaustive. */
    timeseries: Junction.TemperatureTimeseriesExprTimeseries;
    /** ℹ️ This enum is non-exhaustive. */
    field: Junction.TemperatureTimeseriesExprField;
}
