// This file was auto-generated by Fern from our API Definition.

export interface TimeSlot {
    bookingKey?: string | null;
    /** Time is in UTC */
    start: Date;
    /** Time is in UTC */
    end: Date;
    expiresAt?: Date | null;
    price: number;
    isPriority: boolean;
    numAppointmentsAvailable: number;
}
