// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const UnmatchedResultResolutionAction = {
    Reject: "reject",
    Unsure: "unsure",
} as const;
export type UnmatchedResultResolutionAction =
    (typeof UnmatchedResultResolutionAction)[keyof typeof UnmatchedResultResolutionAction];
