// This file was auto-generated by Fern from our API Definition.

/** Subset of `MatchReviewTransitionStatus` a customer may move a result to. ℹ️ This enum is non-exhaustive. */
export const UnmatchedResultUpdateStatus = {
    PendingCustomerReview: "pending_customer_review",
    PendingCustomerReviewInProgress: "pending_customer_review:in_progress",
} as const;
export type UnmatchedResultUpdateStatus =
    (typeof UnmatchedResultUpdateStatus)[keyof typeof UnmatchedResultUpdateStatus];
