// This file was auto-generated by Fern from our API Definition.

/** ℹ️ This enum is non-exhaustive. */
export const UnmatchedResultTestRunStatus = {
    Queued: "queued",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
} as const;
export type UnmatchedResultTestRunStatus =
    (typeof UnmatchedResultTestRunStatus)[keyof typeof UnmatchedResultTestRunStatus];
