// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../index.js";

/**
 * FROM clause variant: unnest a list column into elements.
 */
export interface UnnestExpr {
    unnest: Junction.UnnestExprUnnest;
}
