// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UserCreateBody: core.serialization.Schema<serializers.UserCreateBody.Raw, Junction.UserCreateBody> =
    core.serialization.object({
        clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
        fallbackTimeZone: core.serialization.property(
            "fallback_time_zone",
            core.serialization.string().optionalNullable(),
        ),
        fallbackBirthDate: core.serialization.property(
            "fallback_birth_date",
            core.serialization.string().optionalNullable(),
        ),
        ingestionStart: core.serialization.property("ingestion_start", core.serialization.string().optionalNullable()),
        ingestionEnd: core.serialization.property("ingestion_end", core.serialization.string().optionalNullable()),
    });

export declare namespace UserCreateBody {
    export interface Raw {
        client_user_id: string;
        fallback_time_zone?: (string | null | undefined) | null;
        fallback_birth_date?: (string | null | undefined) | null;
        ingestion_start?: (string | null | undefined) | null;
        ingestion_end?: (string | null | undefined) | null;
    }
}
