// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { CheckoutSessionPayment } from "../../../../types/CheckoutSessionPayment.js";
import { PatientAddressWithValidation } from "../../../../types/PatientAddressWithValidation.js";
import { PatientDetailsWithValidation } from "../../../../types/PatientDetailsWithValidation.js";

export const CreateCheckoutSessionBody: core.serialization.Schema<
    serializers.CreateCheckoutSessionBody.Raw,
    Omit<Junction.CreateCheckoutSessionBody, "idempotencyKey">
> = core.serialization.object({
    quoteId: core.serialization.property("quote_id", core.serialization.string()),
    userId: core.serialization.property("user_id", core.serialization.string()),
    payment: CheckoutSessionPayment,
    patientDetails: core.serialization.property("patient_details", PatientDetailsWithValidation),
    patientAddress: core.serialization.property("patient_address", PatientAddressWithValidation),
});

export declare namespace CreateCheckoutSessionBody {
    export interface Raw {
        quote_id: string;
        user_id: string;
        payment: CheckoutSessionPayment.Raw;
        patient_details: PatientDetailsWithValidation.Raw;
        patient_address: PatientAddressWithValidation.Raw;
    }
}
