// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { Address } from "../../../../types/Address.js";
import { PayorCodeExternalProvider } from "../../../../types/PayorCodeExternalProvider.js";

export const CreatePayorBody: core.serialization.Schema<serializers.CreatePayorBody.Raw, Junction.CreatePayorBody> =
    core.serialization.object({
        name: core.serialization.string(),
        address: Address,
        provider: PayorCodeExternalProvider.optionalNullable(),
        providerPayorId: core.serialization.property(
            "provider_payor_id",
            core.serialization.string().optionalNullable(),
        ),
    });

export declare namespace CreatePayorBody {
    export interface Raw {
        name: string;
        address: Address.Raw;
        provider?: (PayorCodeExternalProvider.Raw | null | undefined) | null;
        provider_payor_id?: (string | null | undefined) | null;
    }
}
