// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         userId: "user_id",
 *         timeframe: {
 *             type: "relative",
 *             anchor: "anchor",
 *             past: {
 *                 unit: "minute"
 *             }
 *         },
 *         queries: [{
 *                 select: [{
 *                         arg: {
 *                             sleep: "id"
 *                         },
 *                         func: "mean"
 *                     }]
 *             }]
 *     }
 */
export interface QueryBatch {
    userId: string;
    timeframe: Junction.QueryBatchTimeframe;
    queries: Junction.Query[];
    config?: Junction.QueryConfig;
}
