// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         sampleId: "sample_id",
 *         patientDetails: {
 *             firstName: "first_name",
 *             lastName: "last_name",
 *             dob: "dob",
 *             gender: "female",
 *             phoneNumber: "phone_number",
 *             email: "email"
 *         },
 *         patientAddress: {
 *             firstLine: "first_line",
 *             city: "city",
 *             state: "state",
 *             zip: "zip",
 *             country: "country"
 *         }
 *     }
 */
export interface RegisterTestkitRequest {
    /** The user ID of the patient. If it differs from the user currently associated with the unregistered testkit order, the order is rebound to this user at registration time. The user must exist on the same team as the order. If omitted, the order's existing user is kept. */
    userId?: string | null;
    sampleId: string;
    patientDetails: Junction.PatientDetailsWithValidation;
    patientAddress: Junction.PatientAddressWithValidation;
    physician?: Junction.PhysicianCreateRequestBase | null;
    healthInsurance?: Junction.HealthInsuranceCreateRequest | null;
    consents?: Junction.Consent[];
}
