// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AddOnOrder: core.serialization.ObjectSchema<serializers.AddOnOrder.Raw, Junction.AddOnOrder> =
    core.serialization.object({
        markerIds: core.serialization.property(
            "marker_ids",
            core.serialization.list(core.serialization.number()).optionalNullable(),
        ),
        providerIds: core.serialization.property(
            "provider_ids",
            core.serialization.list(core.serialization.string()).optionalNullable(),
        ),
    });

export declare namespace AddOnOrder {
    export interface Raw {
        marker_ids?: (number[] | null | undefined) | null;
        provider_ids?: (string[] | null | undefined) | null;
    }
}
