// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Address: core.serialization.ObjectSchema<serializers.Address.Raw, Junction.Address> =
    core.serialization.object({
        firstLine: core.serialization.property("first_line", core.serialization.string()),
        secondLine: core.serialization.property("second_line", core.serialization.string().optionalNullable()),
        country: core.serialization.string(),
        zip: core.serialization.string(),
        city: core.serialization.string(),
        state: core.serialization.string(),
        accessNotes: core.serialization.property("access_notes", core.serialization.string().optionalNullable()),
    });

export declare namespace Address {
    export interface Raw {
        first_line: string;
        second_line?: (string | null | undefined) | null;
        country: string;
        zip: string;
        city: string;
        state: string;
        access_notes?: (string | null | undefined) | null;
    }
}
