// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AggregateFieldExprFunc: core.serialization.Schema<
    serializers.AggregateFieldExprFunc.Raw,
    Junction.AggregateFieldExprFunc
> = core.serialization.enum_(["mean", "min", "max", "sum", "count", "median", "stddev", "oldest", "newest"]);

export declare namespace AggregateFieldExprFunc {
    export type Raw = "mean" | "min" | "max" | "sum" | "count" | "median" | "stddev" | "oldest" | "newest";
}
