// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ElementFieldExpr } from "./ElementFieldExpr.js";
import { McBasalBodyTemperatureFieldExpr } from "./McBasalBodyTemperatureFieldExpr.js";
import { McCervicalMucusFieldExpr } from "./McCervicalMucusFieldExpr.js";
import { McContraceptiveFieldExpr } from "./McContraceptiveFieldExpr.js";
import { McDetectedDeviationsFieldExpr } from "./McDetectedDeviationsFieldExpr.js";
import { McHomePregnancyTestFieldExpr } from "./McHomePregnancyTestFieldExpr.js";
import { McHomeProgesteroneTestFieldExpr } from "./McHomeProgesteroneTestFieldExpr.js";
import { McIntermenstrualBleedingFieldExpr } from "./McIntermenstrualBleedingFieldExpr.js";
import { McMenstrualFlowFieldExpr } from "./McMenstrualFlowFieldExpr.js";
import { McOvulationTestFieldExpr } from "./McOvulationTestFieldExpr.js";
import { McSexualActivityFieldExpr } from "./McSexualActivityFieldExpr.js";

export const AggregateFieldExprArg: core.serialization.Schema<
    serializers.AggregateFieldExprArg.Raw,
    Junction.AggregateFieldExprArg
> = core.serialization.undiscriminatedUnion([
    McMenstrualFlowFieldExpr,
    McCervicalMucusFieldExpr,
    McIntermenstrualBleedingFieldExpr,
    McContraceptiveFieldExpr,
    McDetectedDeviationsFieldExpr,
    McOvulationTestFieldExpr,
    McHomePregnancyTestFieldExpr,
    McHomeProgesteroneTestFieldExpr,
    McSexualActivityFieldExpr,
    McBasalBodyTemperatureFieldExpr,
    ElementFieldExpr,
]);

export declare namespace AggregateFieldExprArg {
    export type Raw =
        | McMenstrualFlowFieldExpr.Raw
        | McCervicalMucusFieldExpr.Raw
        | McIntermenstrualBleedingFieldExpr.Raw
        | McContraceptiveFieldExpr.Raw
        | McDetectedDeviationsFieldExpr.Raw
        | McOvulationTestFieldExpr.Raw
        | McHomePregnancyTestFieldExpr.Raw
        | McHomeProgesteroneTestFieldExpr.Raw
        | McSexualActivityFieldExpr.Raw
        | McBasalBodyTemperatureFieldExpr.Raw
        | ElementFieldExpr.Raw;
}
