// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AppointmentBookingRequest: core.serialization.ObjectSchema<
    serializers.AppointmentBookingRequest.Raw,
    Junction.AppointmentBookingRequest
> = core.serialization.object({
    bookingKey: core.serialization.property("booking_key", core.serialization.string()),
    appointmentNotes: core.serialization.property("appointment_notes", core.serialization.string().optionalNullable()),
    asyncConfirmation: core.serialization.property("async_confirmation", core.serialization.boolean().optional()),
    syncConfirmationTimeoutMillisecond: core.serialization.property(
        "sync_confirmation_timeout_millisecond",
        core.serialization.number().optionalNullable(),
    ),
    asyncConfirmationTimeoutMillisecond: core.serialization.property(
        "async_confirmation_timeout_millisecond",
        core.serialization.number().optionalNullable(),
    ),
});

export declare namespace AppointmentBookingRequest {
    export interface Raw {
        booking_key: string;
        appointment_notes?: (string | null | undefined) | null;
        async_confirmation?: boolean | null;
        sync_confirmation_timeout_millisecond?: (number | null | undefined) | null;
        async_confirmation_timeout_millisecond?: (number | null | undefined) | null;
    }
}
