// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AppointmentServiceType: core.serialization.Schema<
    serializers.AppointmentServiceType.Raw,
    Junction.AppointmentServiceType
> = core.serialization.enum_(["appointment-ready", "appointment-request"]);

export declare namespace AppointmentServiceType {
    export type Raw = "appointment-ready" | "appointment-request";
}
