// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AppointmentType: core.serialization.Schema<serializers.AppointmentType.Raw, Junction.AppointmentType> =
    core.serialization.enum_(["phlebotomy", "patient_service_center"]);

export declare namespace AppointmentType {
    export type Raw = "phlebotomy" | "patient_service_center";
}
