// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LngLat } from "./LngLat.js";
import { UsAddress } from "./UsAddress.js";

export const AppointmentLocation: core.serialization.ObjectSchema<
    serializers.AppointmentLocation.Raw,
    Junction.AppointmentLocation
> = core.serialization.object({
    location: LngLat,
    distance: core.serialization.number().optionalNullable(),
    address: UsAddress,
    code: core.serialization.string(),
    name: core.serialization.string(),
    ianaTimezone: core.serialization.property("iana_timezone", core.serialization.string().optionalNullable()),
});

export declare namespace AppointmentLocation {
    export interface Raw {
        location: LngLat.Raw;
        distance?: (number | null | undefined) | null;
        address: UsAddress.Raw;
        code: string;
        name: string;
        iana_timezone?: (string | null | undefined) | null;
    }
}
