// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ParentBiomarkerData } from "./ParentBiomarkerData.js";
import { ResultType } from "./ResultType.js";

export const BiomarkerResult: core.serialization.ObjectSchema<
    serializers.BiomarkerResult.Raw,
    Junction.BiomarkerResult
> = core.serialization.object({
    name: core.serialization.string(),
    slug: core.serialization.string().optional(),
    result: core.serialization.string(),
    type: ResultType,
    unit: core.serialization.string().optionalNullable(),
    timestamp: core.serialization.date().optionalNullable(),
    notes: core.serialization.string().optionalNullable(),
    referenceRange: core.serialization.property("reference_range", core.serialization.string().optionalNullable()),
    minRangeValue: core.serialization.property("min_range_value", core.serialization.number().optionalNullable()),
    maxRangeValue: core.serialization.property("max_range_value", core.serialization.number().optionalNullable()),
    isAboveMaxRange: core.serialization.property("is_above_max_range", core.serialization.boolean().optionalNullable()),
    isBelowMinRange: core.serialization.property("is_below_min_range", core.serialization.boolean().optionalNullable()),
    interpretation: core.serialization.string().optional(),
    loinc: core.serialization.string().optionalNullable(),
    loincSlug: core.serialization.property("loinc_slug", core.serialization.string().optionalNullable()),
    providerId: core.serialization.property("provider_id", core.serialization.string().optionalNullable()),
    sourceMarkers: core.serialization.property(
        "source_markers",
        core.serialization.list(ParentBiomarkerData).optionalNullable(),
    ),
    performingLaboratory: core.serialization.property(
        "performing_laboratory",
        core.serialization.string().optionalNullable(),
    ),
    sourceSampleId: core.serialization.property("source_sample_id", core.serialization.string().optionalNullable()),
});

export declare namespace BiomarkerResult {
    export interface Raw {
        name: string;
        slug?: string | null;
        result: string;
        type: ResultType.Raw;
        unit?: (string | null | undefined) | null;
        timestamp?: (string | null | undefined) | null;
        notes?: (string | null | undefined) | null;
        reference_range?: (string | null | undefined) | null;
        min_range_value?: (number | null | undefined) | null;
        max_range_value?: (number | null | undefined) | null;
        is_above_max_range?: (boolean | null | undefined) | null;
        is_below_min_range?: (boolean | null | undefined) | null;
        interpretation?: string | null;
        loinc?: (string | null | undefined) | null;
        loinc_slug?: (string | null | undefined) | null;
        provider_id?: (string | null | undefined) | null;
        source_markers?: (ParentBiomarkerData.Raw[] | null | undefined) | null;
        performing_laboratory?: (string | null | undefined) | null;
        source_sample_id?: (string | null | undefined) | null;
    }
}
