// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CanonicalCandidate: core.serialization.ObjectSchema<
    serializers.CanonicalCandidate.Raw,
    Junction.CanonicalCandidate
> = core.serialization.object({
    loincSetHash: core.serialization.property("loinc_set_hash", core.serialization.string()),
    displayName: core.serialization.property("display_name", core.serialization.string()),
    aliases: core.serialization.list(core.serialization.string()).optional(),
    loincCodes: core.serialization.property(
        "loinc_codes",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    providerIds: core.serialization.property(
        "provider_ids",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    loincComponents: core.serialization.property(
        "loinc_components",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    loincGroups: core.serialization.property(
        "loinc_groups",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    cptCodes: core.serialization.property("cpt_codes", core.serialization.list(core.serialization.string()).optional()),
    popularityScore: core.serialization.property("popularity_score", core.serialization.number()),
    confidence: core.serialization.number(),
});

export declare namespace CanonicalCandidate {
    export interface Raw {
        loinc_set_hash: string;
        display_name: string;
        aliases?: string[] | null;
        loinc_codes?: string[] | null;
        provider_ids?: string[] | null;
        loinc_components?: string[] | null;
        loinc_groups?: string[] | null;
        cpt_codes?: string[] | null;
        popularity_score: number;
        confidence: number;
    }
}
