// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CheckoutSessionPaymentMethod } from "./CheckoutSessionPaymentMethod.js";

export const CheckoutSessionPayment: core.serialization.ObjectSchema<
    serializers.CheckoutSessionPayment.Raw,
    Junction.CheckoutSessionPayment
> = core.serialization.object({
    channel: core.serialization.stringLiteral("stripe"),
    method: CheckoutSessionPaymentMethod,
    successUrl: core.serialization.property("success_url", core.serialization.string().optionalNullable()),
    cancelUrl: core.serialization.property("cancel_url", core.serialization.string().optionalNullable()),
});

export declare namespace CheckoutSessionPayment {
    export interface Raw {
        channel: "stripe";
        method: CheckoutSessionPaymentMethod.Raw;
        success_url?: (string | null | undefined) | null;
        cancel_url?: (string | null | undefined) | null;
    }
}
