// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CheckoutSessionStatus } from "./CheckoutSessionStatus.js";

export const CheckoutSession: core.serialization.ObjectSchema<
    serializers.CheckoutSession.Raw,
    Junction.CheckoutSession
> = core.serialization.object({
    checkoutSessionId: core.serialization.property("checkout_session_id", core.serialization.string()),
    status: CheckoutSessionStatus,
    payBefore: core.serialization.property("pay_before", core.serialization.date()),
    paymentResourceId: core.serialization.property(
        "payment_resource_id",
        core.serialization.string().optionalNullable(),
    ),
    paymentResourceUrl: core.serialization.property(
        "payment_resource_url",
        core.serialization.string().optionalNullable(),
    ),
    paymentResourceClientSecret: core.serialization.property(
        "payment_resource_client_secret",
        core.serialization.string().optionalNullable(),
    ),
    orderId: core.serialization.property("order_id", core.serialization.string().optionalNullable()),
    orderTransactionId: core.serialization.property(
        "order_transaction_id",
        core.serialization.string().optionalNullable(),
    ),
});

export declare namespace CheckoutSession {
    export interface Raw {
        checkout_session_id: string;
        status: CheckoutSessionStatus.Raw;
        pay_before: string;
        payment_resource_id?: (string | null | undefined) | null;
        payment_resource_url?: (string | null | undefined) | null;
        payment_resource_client_secret?: (string | null | undefined) | null;
        order_id?: (string | null | undefined) | null;
        order_transaction_id?: (string | null | undefined) | null;
    }
}
