// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CheckoutQuoteLineItemCode: core.serialization.Schema<
    serializers.CheckoutQuoteLineItemCode.Raw,
    Junction.CheckoutQuoteLineItemCode
> = core.serialization.enum_(["lab_test_fee", "draw_fee"]);

export declare namespace CheckoutQuoteLineItemCode {
    export type Raw = "lab_test_fee" | "draw_fee";
}
