// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CheckoutSessionAppointment: core.serialization.ObjectSchema<
    serializers.CheckoutSessionAppointment.Raw,
    Junction.CheckoutSessionAppointment
> = core.serialization.object({
    bookingKey: core.serialization.property("booking_key", core.serialization.string()),
    appointmentNotes: core.serialization.property("appointment_notes", core.serialization.string()),
    asyncConfirmationTimeoutMillisecond: core.serialization.property(
        "async_confirmation_timeout_millisecond",
        core.serialization.number().optional(),
    ),
});

export declare namespace CheckoutSessionAppointment {
    export interface Raw {
        booking_key: string;
        appointment_notes: string;
        async_confirmation_timeout_millisecond?: number | null;
    }
}
