// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CheckoutAppointmentHoldStatus: core.serialization.Schema<
    serializers.CheckoutAppointmentHoldStatus.Raw,
    Junction.CheckoutAppointmentHoldStatus
> = core.serialization.enum_(["pending", "held", "failed"]);

export declare namespace CheckoutAppointmentHoldStatus {
    export type Raw = "pending" | "held" | "failed";
}
