// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingHeartRate: core.serialization.ObjectSchema<
    serializers.ClientFacingHeartRate.Raw,
    Junction.ClientFacingHeartRate
> = core.serialization.object({
    avgBpm: core.serialization.property("avg_bpm", core.serialization.number().optionalNullable()),
    minBpm: core.serialization.property("min_bpm", core.serialization.number().optionalNullable()),
    maxBpm: core.serialization.property("max_bpm", core.serialization.number().optionalNullable()),
    restingBpm: core.serialization.property("resting_bpm", core.serialization.number().optionalNullable()),
    avgWalkingBpm: core.serialization.property("avg_walking_bpm", core.serialization.number().optionalNullable()),
});

export declare namespace ClientFacingHeartRate {
    export interface Raw {
        avg_bpm?: (number | null | undefined) | null;
        min_bpm?: (number | null | undefined) | null;
        max_bpm?: (number | null | undefined) | null;
        resting_bpm?: (number | null | undefined) | null;
        avg_walking_bpm?: (number | null | undefined) | null;
    }
}
