// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Labs } from "./Labs.js";
import { Providers } from "./Providers.js";

export const ClientFacingSleepCycleSourceProvider: core.serialization.Schema<
    serializers.ClientFacingSleepCycleSourceProvider.Raw,
    Junction.ClientFacingSleepCycleSourceProvider
> = core.serialization.undiscriminatedUnion([Providers, Labs]);

export declare namespace ClientFacingSleepCycleSourceProvider {
    export type Raw = Providers.Raw | Labs.Raw;
}
