// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingDeviceChangedEventType: core.serialization.Schema<
    serializers.ClientFacingDeviceChangedEventType.Raw,
    Junction.ClientFacingDeviceChangedEventType
> = core.serialization.enum_(["provider.device.created", "provider.device.updated"]);

export declare namespace ClientFacingDeviceChangedEventType {
    export type Raw = "provider.device.created" | "provider.device.updated";
}
