// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingWorkoutDurationSampleIntensity } from "./ClientFacingWorkoutDurationSampleIntensity.js";

export const ClientFacingWorkoutDurationSample: core.serialization.ObjectSchema<
    serializers.ClientFacingWorkoutDurationSample.Raw,
    Junction.ClientFacingWorkoutDurationSample
> = core.serialization.object({
    id: core.serialization.number().optionalNullable(),
    timezoneOffset: core.serialization.property("timezone_offset", core.serialization.number().optionalNullable()),
    type: core.serialization.string().optionalNullable(),
    unit: core.serialization.stringLiteral("min"),
    timestamp: core.serialization.date(),
    start: core.serialization.date(),
    end: core.serialization.date(),
    value: core.serialization.number(),
    intensity: ClientFacingWorkoutDurationSampleIntensity.optionalNullable(),
});

export declare namespace ClientFacingWorkoutDurationSample {
    export interface Raw {
        id?: (number | null | undefined) | null;
        timezone_offset?: (number | null | undefined) | null;
        type?: (string | null | undefined) | null;
        unit: "min";
        timestamp: string;
        start: string;
        end: string;
        value: number;
        intensity?: (ClientFacingWorkoutDurationSampleIntensity.Raw | null | undefined) | null;
    }
}
