// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingMindfulnessMinutesChangedEventType: core.serialization.Schema<
    serializers.ClientFacingMindfulnessMinutesChangedEventType.Raw,
    Junction.ClientFacingMindfulnessMinutesChangedEventType
> = core.serialization.enum_(["daily.data.mindfulness_minutes.created", "daily.data.mindfulness_minutes.updated"]);

export declare namespace ClientFacingMindfulnessMinutesChangedEventType {
    export type Raw = "daily.data.mindfulness_minutes.created" | "daily.data.mindfulness_minutes.updated";
}
