// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MatchReviewWebhookPayload } from "./MatchReviewWebhookPayload.js";

export const ClientFacingMatchReviewUpdated: core.serialization.ObjectSchema<
    serializers.ClientFacingMatchReviewUpdated.Raw,
    Junction.ClientFacingMatchReviewUpdated
> = core.serialization.object({
    eventType: core.serialization.property(
        "event_type",
        core.serialization.stringLiteral("labtest.match_review.updated"),
    ),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: MatchReviewWebhookPayload,
});

export declare namespace ClientFacingMatchReviewUpdated {
    export interface Raw {
        event_type: "labtest.match_review.updated";
        team_id: string;
        data: MatchReviewWebhookPayload.Raw;
    }
}
