// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Billing } from "./Billing.js";
import { ClientFacingLabTest } from "./ClientFacingLabTest.js";
import { ClientFacingOrderDetails } from "./ClientFacingOrderDetails.js";
import { ClientFacingOrderEvent } from "./ClientFacingOrderEvent.js";
import { ClientFacingOrderTransaction } from "./ClientFacingOrderTransaction.js";
import { ClientFacingPatientDetailsCompatible } from "./ClientFacingPatientDetailsCompatible.js";
import { ClientFacingPhysician } from "./ClientFacingPhysician.js";
import { Interpretation } from "./Interpretation.js";
import { OrderOrigin } from "./OrderOrigin.js";
import { OrderTopLevelStatus } from "./OrderTopLevelStatus.js";
import { PatientAddressCompatible } from "./PatientAddressCompatible.js";
import { ShippingAddress } from "./ShippingAddress.js";

export const ClientFacingOrder: core.serialization.ObjectSchema<
    serializers.ClientFacingOrder.Raw,
    Junction.ClientFacingOrder
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    id: core.serialization.string(),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    patientDetails: core.serialization.property(
        "patient_details",
        ClientFacingPatientDetailsCompatible.optionalNullable(),
    ),
    patientAddress: core.serialization.property("patient_address", PatientAddressCompatible.optionalNullable()),
    labTest: core.serialization.property("lab_test", ClientFacingLabTest),
    details: ClientFacingOrderDetails,
    sampleId: core.serialization.property("sample_id", core.serialization.string().optionalNullable()),
    notes: core.serialization.string().optionalNullable(),
    clinicalNotes: core.serialization.property("clinical_notes", core.serialization.string().optionalNullable()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    events: core.serialization.list(ClientFacingOrderEvent),
    status: OrderTopLevelStatus.optionalNullable(),
    lastEvent: core.serialization.property("last_event", ClientFacingOrderEvent),
    physician: ClientFacingPhysician.optionalNullable(),
    healthInsuranceId: core.serialization.property(
        "health_insurance_id",
        core.serialization.string().optionalNullable(),
    ),
    requisitionFormUrl: core.serialization.property(
        "requisition_form_url",
        core.serialization.string().optionalNullable(),
    ),
    priority: core.serialization.boolean().optional(),
    shippingDetails: core.serialization.property("shipping_details", ShippingAddress.optionalNullable()),
    activateBy: core.serialization.property("activate_by", core.serialization.string().optionalNullable()),
    passthrough: core.serialization.string().optionalNullable(),
    billingType: core.serialization.property("billing_type", Billing.optional()),
    icdCodes: core.serialization.property(
        "icd_codes",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
    hasAbn: core.serialization.property("has_abn", core.serialization.boolean()),
    interpretation: Interpretation.optionalNullable(),
    hasMissingResults: core.serialization.property(
        "has_missing_results",
        core.serialization.boolean().optionalNullable(),
    ),
    expectedResultByDate: core.serialization.property(
        "expected_result_by_date",
        core.serialization.string().optionalNullable(),
    ),
    worstCaseResultByDate: core.serialization.property(
        "worst_case_result_by_date",
        core.serialization.string().optionalNullable(),
    ),
    origin: OrderOrigin.optionalNullable(),
    orderTransaction: core.serialization.property("order_transaction", ClientFacingOrderTransaction.optionalNullable()),
});

export declare namespace ClientFacingOrder {
    export interface Raw {
        user_id: string;
        id: string;
        team_id: string;
        patient_details?: (ClientFacingPatientDetailsCompatible.Raw | null | undefined) | null;
        patient_address?: (PatientAddressCompatible.Raw | null | undefined) | null;
        lab_test: ClientFacingLabTest.Raw;
        details: ClientFacingOrderDetails.Raw;
        sample_id?: (string | null | undefined) | null;
        notes?: (string | null | undefined) | null;
        clinical_notes?: (string | null | undefined) | null;
        created_at: string;
        updated_at: string;
        events: ClientFacingOrderEvent.Raw[];
        status?: (OrderTopLevelStatus.Raw | null | undefined) | null;
        last_event: ClientFacingOrderEvent.Raw;
        physician?: (ClientFacingPhysician.Raw | null | undefined) | null;
        health_insurance_id?: (string | null | undefined) | null;
        requisition_form_url?: (string | null | undefined) | null;
        priority?: boolean | null;
        shipping_details?: (ShippingAddress.Raw | null | undefined) | null;
        activate_by?: (string | null | undefined) | null;
        passthrough?: (string | null | undefined) | null;
        billing_type?: Billing.Raw | null;
        icd_codes?: (string[] | null | undefined) | null;
        has_abn: boolean;
        interpretation?: (Interpretation.Raw | null | undefined) | null;
        has_missing_results?: (boolean | null | undefined) | null;
        expected_result_by_date?: (string | null | undefined) | null;
        worst_case_result_by_date?: (string | null | undefined) | null;
        origin?: (OrderOrigin.Raw | null | undefined) | null;
        order_transaction?: (ClientFacingOrderTransaction.Raw | null | undefined) | null;
    }
}
