// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingApiKey: core.serialization.ObjectSchema<
    serializers.ClientFacingApiKey.Raw,
    Junction.ClientFacingApiKey
> = core.serialization.object({
    label: core.serialization.string(),
    value: core.serialization.string(),
    teamId: core.serialization.property("team_id", core.serialization.string().optionalNullable()),
    id: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    deletedAt: core.serialization.property("deleted_at", core.serialization.date().optionalNullable()),
});

export declare namespace ClientFacingApiKey {
    export interface Raw {
        label: string;
        value: string;
        team_id?: (string | null | undefined) | null;
        id: string;
        created_at: string;
        deleted_at?: (string | null | undefined) | null;
    }
}
