// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConnectedSourceClientFacing } from "./ConnectedSourceClientFacing.js";
import { FallbackBirthDate } from "./FallbackBirthDate.js";
import { FallbackTimeZone } from "./FallbackTimeZone.js";

export const ClientFacingUser: core.serialization.ObjectSchema<
    serializers.ClientFacingUser.Raw,
    Junction.ClientFacingUser
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    createdOn: core.serialization.property("created_on", core.serialization.date()),
    connectedSources: core.serialization.property(
        "connected_sources",
        core.serialization.list(ConnectedSourceClientFacing),
    ),
    fallbackTimeZone: core.serialization.property("fallback_time_zone", FallbackTimeZone.optionalNullable()),
    fallbackBirthDate: core.serialization.property("fallback_birth_date", FallbackBirthDate.optionalNullable()),
    ingestionStart: core.serialization.property("ingestion_start", core.serialization.string().optionalNullable()),
    ingestionEnd: core.serialization.property("ingestion_end", core.serialization.string().optionalNullable()),
});

export declare namespace ClientFacingUser {
    export interface Raw {
        user_id: string;
        team_id: string;
        client_user_id: string;
        created_on: string;
        connected_sources: ConnectedSourceClientFacing.Raw[];
        fallback_time_zone?: (FallbackTimeZone.Raw | null | undefined) | null;
        fallback_birth_date?: (FallbackBirthDate.Raw | null | undefined) | null;
        ingestion_start?: (string | null | undefined) | null;
        ingestion_end?: (string | null | undefined) | null;
    }
}
