// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingSleepStream } from "./ClientFacingSleepStream.js";
import { ClientFacingSource } from "./ClientFacingSource.js";
import { SleepSummaryState } from "./SleepSummaryState.js";
import { SleepType } from "./SleepType.js";

export const ClientFacingSleep: core.serialization.ObjectSchema<
    serializers.ClientFacingSleep.Raw,
    Junction.ClientFacingSleep
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    date: core.serialization.date(),
    calendarDate: core.serialization.property("calendar_date", core.serialization.string()),
    bedtimeStart: core.serialization.property("bedtime_start", core.serialization.date()),
    bedtimeStop: core.serialization.property("bedtime_stop", core.serialization.date()),
    type: SleepType,
    timezoneOffset: core.serialization.property("timezone_offset", core.serialization.number().optionalNullable()),
    duration: core.serialization.number(),
    total: core.serialization.number(),
    awake: core.serialization.number(),
    light: core.serialization.number(),
    rem: core.serialization.number(),
    deep: core.serialization.number(),
    score: core.serialization.number().optionalNullable(),
    recoveryReadinessScore: core.serialization.property(
        "recovery_readiness_score",
        core.serialization.number().optionalNullable(),
    ),
    hrLowest: core.serialization.property("hr_lowest", core.serialization.number().optionalNullable()),
    hrAverage: core.serialization.property("hr_average", core.serialization.number().optionalNullable()),
    hrResting: core.serialization.property("hr_resting", core.serialization.number().optionalNullable()),
    efficiency: core.serialization.number().optionalNullable(),
    latency: core.serialization.number().optionalNullable(),
    temperatureDelta: core.serialization.property("temperature_delta", core.serialization.number().optionalNullable()),
    skinTemperature: core.serialization.property("skin_temperature", core.serialization.number().optionalNullable()),
    hrDip: core.serialization.property("hr_dip", core.serialization.number().optionalNullable()),
    state: SleepSummaryState.optionalNullable(),
    averageHrv: core.serialization.property("average_hrv", core.serialization.number().optionalNullable()),
    respiratoryRate: core.serialization.property("respiratory_rate", core.serialization.number().optionalNullable()),
    source: ClientFacingSource,
    sleepStream: core.serialization.property("sleep_stream", ClientFacingSleepStream.optionalNullable()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace ClientFacingSleep {
    export interface Raw {
        id: string;
        user_id: string;
        date: string;
        calendar_date: string;
        bedtime_start: string;
        bedtime_stop: string;
        type: SleepType.Raw;
        timezone_offset?: (number | null | undefined) | null;
        duration: number;
        total: number;
        awake: number;
        light: number;
        rem: number;
        deep: number;
        score?: (number | null | undefined) | null;
        recovery_readiness_score?: (number | null | undefined) | null;
        hr_lowest?: (number | null | undefined) | null;
        hr_average?: (number | null | undefined) | null;
        hr_resting?: (number | null | undefined) | null;
        efficiency?: (number | null | undefined) | null;
        latency?: (number | null | undefined) | null;
        temperature_delta?: (number | null | undefined) | null;
        skin_temperature?: (number | null | undefined) | null;
        hr_dip?: (number | null | undefined) | null;
        state?: (SleepSummaryState.Raw | null | undefined) | null;
        average_hrv?: (number | null | undefined) | null;
        respiratory_rate?: (number | null | undefined) | null;
        source: ClientFacingSource.Raw;
        sleep_stream?: (ClientFacingSleepStream.Raw | null | undefined) | null;
        created_at: string;
        updated_at: string;
    }
}
