// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingWorkoutMap: core.serialization.ObjectSchema<
    serializers.ClientFacingWorkoutMap.Raw,
    Junction.ClientFacingWorkoutMap
> = core.serialization.object({
    polyline: core.serialization.string().optionalNullable(),
    summaryPolyline: core.serialization.property("summary_polyline", core.serialization.string().optionalNullable()),
});

export declare namespace ClientFacingWorkoutMap {
    export interface Raw {
        polyline?: (string | null | undefined) | null;
        summary_polyline?: (string | null | undefined) | null;
    }
}
