// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingHeartRate } from "./ClientFacingHeartRate.js";
import { ClientFacingSource } from "./ClientFacingSource.js";

export const ClientFacingActivity: core.serialization.ObjectSchema<
    serializers.ClientFacingActivity.Raw,
    Junction.ClientFacingActivity
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    date: core.serialization.date(),
    calendarDate: core.serialization.property("calendar_date", core.serialization.string()),
    caloriesTotal: core.serialization.property("calories_total", core.serialization.number().optionalNullable()),
    caloriesActive: core.serialization.property("calories_active", core.serialization.number().optionalNullable()),
    steps: core.serialization.number().optionalNullable(),
    dailyMovement: core.serialization.property("daily_movement", core.serialization.number().optionalNullable()),
    distance: core.serialization.number().optionalNullable(),
    low: core.serialization.number().optionalNullable(),
    medium: core.serialization.number().optionalNullable(),
    high: core.serialization.number().optionalNullable(),
    source: ClientFacingSource,
    floorsClimbed: core.serialization.property("floors_climbed", core.serialization.number().optionalNullable()),
    timeZone: core.serialization.property("time_zone", core.serialization.string().optionalNullable()),
    timezoneOffset: core.serialization.property("timezone_offset", core.serialization.number().optionalNullable()),
    heartRate: core.serialization.property("heart_rate", ClientFacingHeartRate.optionalNullable()),
    wheelchairUse: core.serialization.property(
        "wheelchair_use",
        core.serialization.booleanLiteral(true).optionalNullable(),
    ),
    wheelchairPush: core.serialization.property("wheelchair_push", core.serialization.number().optionalNullable()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace ClientFacingActivity {
    export interface Raw {
        id: string;
        user_id: string;
        date: string;
        calendar_date: string;
        calories_total?: (number | null | undefined) | null;
        calories_active?: (number | null | undefined) | null;
        steps?: (number | null | undefined) | null;
        daily_movement?: (number | null | undefined) | null;
        distance?: (number | null | undefined) | null;
        low?: (number | null | undefined) | null;
        medium?: (number | null | undefined) | null;
        high?: (number | null | undefined) | null;
        source: ClientFacingSource.Raw;
        floors_climbed?: (number | null | undefined) | null;
        time_zone?: (string | null | undefined) | null;
        timezone_offset?: (number | null | undefined) | null;
        heart_rate?: (ClientFacingHeartRate.Raw | null | undefined) | null;
        wheelchair_use?: (true | null | undefined) | null;
        wheelchair_push?: (number | null | undefined) | null;
        created_at: string;
        updated_at: string;
    }
}
