// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Ethnicity } from "./Ethnicity.js";
import { GenderIdentity } from "./GenderIdentity.js";
import { GuarantorDetails } from "./GuarantorDetails.js";
import { Race } from "./Race.js";
import { SexualOrientation } from "./SexualOrientation.js";

export const ClientFacingPatientDetailsCompatible: core.serialization.ObjectSchema<
    serializers.ClientFacingPatientDetailsCompatible.Raw,
    Junction.ClientFacingPatientDetailsCompatible
> = core.serialization.object({
    firstName: core.serialization.property("first_name", core.serialization.string().optionalNullable()),
    lastName: core.serialization.property("last_name", core.serialization.string().optionalNullable()),
    dob: core.serialization.date(),
    gender: core.serialization.string(),
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optionalNullable()),
    email: core.serialization.string().optionalNullable(),
    medicalProxy: core.serialization.property("medical_proxy", GuarantorDetails.optionalNullable()),
    race: Race.optionalNullable(),
    ethnicity: Ethnicity.optionalNullable(),
    sexualOrientation: core.serialization.property("sexual_orientation", SexualOrientation.optionalNullable()),
    genderIdentity: core.serialization.property("gender_identity", GenderIdentity.optionalNullable()),
});

export declare namespace ClientFacingPatientDetailsCompatible {
    export interface Raw {
        first_name?: (string | null | undefined) | null;
        last_name?: (string | null | undefined) | null;
        dob: string;
        gender: string;
        phone_number?: (string | null | undefined) | null;
        email?: (string | null | undefined) | null;
        medical_proxy?: (GuarantorDetails.Raw | null | undefined) | null;
        race?: (Race.Raw | null | undefined) | null;
        ethnicity?: (Ethnicity.Raw | null | undefined) | null;
        sexual_orientation?: (SexualOrientation.Raw | null | undefined) | null;
        gender_identity?: (GenderIdentity.Raw | null | undefined) | null;
    }
}
