// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingWeightChangedEventType: core.serialization.Schema<
    serializers.ClientFacingWeightChangedEventType.Raw,
    Junction.ClientFacingWeightChangedEventType
> = core.serialization.enum_(["daily.data.weight.created", "daily.data.weight.updated"]);

export declare namespace ClientFacingWeightChangedEventType {
    export type Raw = "daily.data.weight.created" | "daily.data.weight.updated";
}
