// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingSource: core.serialization.ObjectSchema<
    serializers.ClientFacingSource.Raw,
    Junction.ClientFacingSource
> = core.serialization.object({
    provider: core.serialization.string(),
    type: core.serialization.string().optional(),
    appId: core.serialization.property("app_id", core.serialization.string().optionalNullable()),
    deviceId: core.serialization.property("device_id", core.serialization.string().optionalNullable()),
    sport: core.serialization.string().optionalNullable(),
    workoutId: core.serialization.property("workout_id", core.serialization.string().optionalNullable()),
    name: core.serialization.string().optional(),
    slug: core.serialization.string().optional(),
    logo: core.serialization.string().optional(),
});

export declare namespace ClientFacingSource {
    export interface Raw {
        provider: string;
        type?: string | null;
        app_id?: (string | null | undefined) | null;
        device_id?: (string | null | undefined) | null;
        sport?: (string | null | undefined) | null;
        workout_id?: (string | null | undefined) | null;
        name?: string | null;
        slug?: string | null;
        logo?: string | null;
    }
}
