// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CheckoutSession } from "./CheckoutSession.js";

export const ClientFacingCheckoutSessionCreated: core.serialization.ObjectSchema<
    serializers.ClientFacingCheckoutSessionCreated.Raw,
    Junction.ClientFacingCheckoutSessionCreated
> = core.serialization.object({
    eventType: core.serialization.property("event_type", core.serialization.stringLiteral("checkout.session.created")),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: CheckoutSession,
});

export declare namespace ClientFacingCheckoutSessionCreated {
    export interface Raw {
        event_type: "checkout.session.created";
        team_id: string;
        data: CheckoutSession.Raw;
    }
}
