// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ParsingJob } from "./ParsingJob.js";

export const ClientFacingLabReportParsingJobCreatedEvent: core.serialization.ObjectSchema<
    serializers.ClientFacingLabReportParsingJobCreatedEvent.Raw,
    Junction.ClientFacingLabReportParsingJobCreatedEvent
> = core.serialization.object({
    eventType: core.serialization.property(
        "event_type",
        core.serialization.stringLiteral("lab_report.parsing_job.created"),
    ),
    userId: core.serialization.property("user_id", core.serialization.string()),
    clientUserId: core.serialization.property("client_user_id", core.serialization.string()),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: ParsingJob,
});

export declare namespace ClientFacingLabReportParsingJobCreatedEvent {
    export interface Raw {
        event_type: "lab_report.parsing_job.created";
        user_id: string;
        client_user_id: string;
        team_id: string;
        data: ParsingJob.Raw;
    }
}
