// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LabAccountDelegatedFlow } from "./LabAccountDelegatedFlow.js";
import { LabAccountStatus } from "./LabAccountStatus.js";
import { Labs } from "./Labs.js";
import { UsState } from "./UsState.js";

export const ClientFacingLabAccount: core.serialization.ObjectSchema<
    serializers.ClientFacingLabAccount.Raw,
    Junction.ClientFacingLabAccount
> = core.serialization.object({
    id: core.serialization.string(),
    lab: Labs,
    orgId: core.serialization.property("org_id", core.serialization.string().optionalNullable()),
    status: LabAccountStatus,
    delegatedFlow: core.serialization.property("delegated_flow", LabAccountDelegatedFlow),
    providerAccountId: core.serialization.property("provider_account_id", core.serialization.string()),
    accountName: core.serialization.property("account_name", core.serialization.string().optionalNullable()),
    defaultClinicalNotes: core.serialization.property(
        "default_clinical_notes",
        core.serialization.string().optionalNullable(),
    ),
    businessUnits: core.serialization.property(
        "business_units",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
    allowedBilling: core.serialization.property(
        "allowed_billing",
        core.serialization.record(core.serialization.string(), core.serialization.list(UsState)),
    ),
    teamIdAllowlist: core.serialization.property(
        "team_id_allowlist",
        core.serialization.list(core.serialization.string()),
    ),
});

export declare namespace ClientFacingLabAccount {
    export interface Raw {
        id: string;
        lab: Labs.Raw;
        org_id?: (string | null | undefined) | null;
        status: LabAccountStatus.Raw;
        delegated_flow: LabAccountDelegatedFlow.Raw;
        provider_account_id: string;
        account_name?: (string | null | undefined) | null;
        default_clinical_notes?: (string | null | undefined) | null;
        business_units?: (string[] | null | undefined) | null;
        allowed_billing: Record<string, UsState.Raw[]>;
        team_id_allowlist: string[];
    }
}
