// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingNoteSampleTagsItem } from "./ClientFacingNoteSampleTagsItem.js";

export const ClientFacingNoteSample: core.serialization.ObjectSchema<
    serializers.ClientFacingNoteSample.Raw,
    Junction.ClientFacingNoteSample
> = core.serialization.object({
    id: core.serialization.number().optionalNullable(),
    timezoneOffset: core.serialization.property("timezone_offset", core.serialization.number().optionalNullable()),
    type: core.serialization.string().optionalNullable(),
    unit: core.serialization.string(),
    timestamp: core.serialization.date(),
    start: core.serialization.date(),
    end: core.serialization.date(),
    value: core.serialization.string(),
    tags: core.serialization.list(ClientFacingNoteSampleTagsItem).optionalNullable(),
});

export declare namespace ClientFacingNoteSample {
    export interface Raw {
        id?: (number | null | undefined) | null;
        timezone_offset?: (number | null | undefined) | null;
        type?: (string | null | undefined) | null;
        unit: string;
        timestamp: string;
        start: string;
        end: string;
        value: string;
        tags?: (ClientFacingNoteSampleTagsItem.Raw[] | null | undefined) | null;
    }
}
