// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingElectrocardiogramChangedEventType: core.serialization.Schema<
    serializers.ClientFacingElectrocardiogramChangedEventType.Raw,
    Junction.ClientFacingElectrocardiogramChangedEventType
> = core.serialization.enum_(["daily.data.electrocardiogram.created", "daily.data.electrocardiogram.updated"]);

export declare namespace ClientFacingElectrocardiogramChangedEventType {
    export type Raw = "daily.data.electrocardiogram.created" | "daily.data.electrocardiogram.updated";
}
