// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingWalkInTestOrder } from "./ClientFacingWalkInTestOrder.js";

export const ClientFacingWalkInOrderDetails: core.serialization.ObjectSchema<
    serializers.ClientFacingWalkInOrderDetails.Raw,
    Junction.ClientFacingWalkInOrderDetails
> = core.serialization.object({
    data: ClientFacingWalkInTestOrder.optionalNullable(),
});

export declare namespace ClientFacingWalkInOrderDetails {
    export interface Raw {
        data?: (ClientFacingWalkInTestOrder.Raw | null | undefined) | null;
    }
}
