// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingResource } from "./ClientFacingResource.js";
import { SourceAuthType } from "./SourceAuthType.js";

export const ClientFacingProviderDetailed: core.serialization.ObjectSchema<
    serializers.ClientFacingProviderDetailed.Raw,
    Junction.ClientFacingProviderDetailed
> = core.serialization.object({
    name: core.serialization.string(),
    slug: core.serialization.string(),
    description: core.serialization.string(),
    logo: core.serialization.string().optionalNullable(),
    authType: core.serialization.property("auth_type", SourceAuthType.optionalNullable()),
    supportedResources: core.serialization.property(
        "supported_resources",
        core.serialization.list(ClientFacingResource).optional(),
    ),
});

export declare namespace ClientFacingProviderDetailed {
    export interface Raw {
        name: string;
        slug: string;
        description: string;
        logo?: (string | null | undefined) | null;
        auth_type?: (SourceAuthType.Raw | null | undefined) | null;
        supported_resources?: ClientFacingResource.Raw[] | null;
    }
}
