// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingInsulinInjectionSampleBolusPurpose: core.serialization.Schema<
    serializers.ClientFacingInsulinInjectionSampleBolusPurpose.Raw,
    Junction.ClientFacingInsulinInjectionSampleBolusPurpose
> = core.serialization.enum_(["meal", "correction", "mixed", "unknown"]);

export declare namespace ClientFacingInsulinInjectionSampleBolusPurpose {
    export type Raw = "meal" | "correction" | "mixed" | "unknown";
}
