// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CheckoutSession } from "./CheckoutSession.js";

export const ClientFacingCheckoutSessionUpdated: core.serialization.ObjectSchema<
    serializers.ClientFacingCheckoutSessionUpdated.Raw,
    Junction.ClientFacingCheckoutSessionUpdated
> = core.serialization.object({
    eventType: core.serialization.property("event_type", core.serialization.stringLiteral("checkout.session.updated")),
    teamId: core.serialization.property("team_id", core.serialization.string()),
    data: CheckoutSession,
});

export declare namespace ClientFacingCheckoutSessionUpdated {
    export interface Raw {
        event_type: "checkout.session.updated";
        team_id: string;
        data: CheckoutSession.Raw;
    }
}
