// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingStreamTemperature: core.serialization.Schema<
    serializers.ClientFacingStreamTemperature.Raw,
    Junction.ClientFacingStreamTemperature
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(core.serialization.number().optionalNullable()),
    core.serialization.list(core.serialization.number()),
]);

export declare namespace ClientFacingStreamTemperature {
    export type Raw = ((number | null | undefined) | null | undefined)[] | number[];
}
