// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ClientFacingWorkoutsChangedEventType: core.serialization.Schema<
    serializers.ClientFacingWorkoutsChangedEventType.Raw,
    Junction.ClientFacingWorkoutsChangedEventType
> = core.serialization.enum_(["daily.data.workouts.created", "daily.data.workouts.updated"]);

export declare namespace ClientFacingWorkoutsChangedEventType {
    export type Raw = "daily.data.workouts.created" | "daily.data.workouts.updated";
}
