// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnmatchedResultTestRunStatus } from "./UnmatchedResultTestRunStatus.js";

export const CreateUnmatchedResultTestResponse: core.serialization.ObjectSchema<
    serializers.CreateUnmatchedResultTestResponse.Raw,
    Junction.CreateUnmatchedResultTestResponse
> = core.serialization.object({
    runId: core.serialization.property("run_id", core.serialization.string()),
    status: UnmatchedResultTestRunStatus,
});

export declare namespace CreateUnmatchedResultTestResponse {
    export interface Raw {
        run_id: string;
        status: UnmatchedResultTestRunStatus.Raw;
    }
}
