// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DerivedReadinessColumnExprDerivedReadiness } from "./DerivedReadinessColumnExprDerivedReadiness.js";

export const DerivedReadinessColumnExpr: core.serialization.ObjectSchema<
    serializers.DerivedReadinessColumnExpr.Raw,
    Junction.DerivedReadinessColumnExpr
> = core.serialization.object({
    derivedReadiness: core.serialization.property("derived_readiness", DerivedReadinessColumnExprDerivedReadiness),
});

export declare namespace DerivedReadinessColumnExpr {
    export interface Raw {
        derived_readiness: DerivedReadinessColumnExprDerivedReadiness.Raw;
    }
}
