// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EventDestinationPreferencesPreferred: core.serialization.Schema<
    serializers.EventDestinationPreferencesPreferred.Raw,
    Junction.EventDestinationPreferencesPreferred
> = core.serialization.enum_(["cloud_pubsub", "rabbitmq", "svix", "azure_amqp"]);

export declare namespace EventDestinationPreferencesPreferred {
    export type Raw = "cloud_pubsub" | "rabbitmq" | "svix" | "azure_amqp";
}
