// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FallbackBirthDate: core.serialization.ObjectSchema<
    serializers.FallbackBirthDate.Raw,
    Junction.FallbackBirthDate
> = core.serialization.object({
    value: core.serialization.string(),
    sourceSlug: core.serialization.property("source_slug", core.serialization.string()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace FallbackBirthDate {
    export interface Raw {
        value: string;
        source_slug: string;
        updated_at: string;
    }
}
