// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SpecifiedPricingComponentPricingConditions } from "./SpecifiedPricingComponentPricingConditions.js";
import { UnspecifiedPricing } from "./UnspecifiedPricing.js";

export const GenericPricingComponentPricing: core.serialization.Schema<
    serializers.GenericPricingComponentPricing.Raw,
    Junction.GenericPricingComponentPricing
> = core.serialization.undiscriminatedUnion([SpecifiedPricingComponentPricingConditions, UnspecifiedPricing]);

export declare namespace GenericPricingComponentPricing {
    export type Raw = SpecifiedPricingComponentPricingConditions.Raw | UnspecifiedPricing.Raw;
}
