// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingMarkerComplete } from "./ClientFacingMarkerComplete.js";

export const GetMarkersResponse: core.serialization.ObjectSchema<
    serializers.GetMarkersResponse.Raw,
    Junction.GetMarkersResponse
> = core.serialization.object({
    markers: core.serialization.list(ClientFacingMarkerComplete),
    total: core.serialization.number().optionalNullable(),
    page: core.serialization.number().optionalNullable(),
    size: core.serialization.number().optionalNullable(),
    pages: core.serialization.number().optionalNullable(),
});

export declare namespace GetMarkersResponse {
    export interface Raw {
        markers: ClientFacingMarkerComplete.Raw[];
        total?: (number | null | undefined) | null;
        page?: (number | null | undefined) | null;
        size?: (number | null | undefined) | null;
        pages?: (number | null | undefined) | null;
    }
}
