// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingOrder } from "./ClientFacingOrder.js";

export const GetOrdersResponse: core.serialization.ObjectSchema<
    serializers.GetOrdersResponse.Raw,
    Junction.GetOrdersResponse
> = core.serialization.object({
    orders: core.serialization.list(ClientFacingOrder),
    total: core.serialization.number().optionalNullable(),
    page: core.serialization.number().optionalNullable(),
    size: core.serialization.number().optionalNullable(),
});

export declare namespace GetOrdersResponse {
    export interface Raw {
        orders: ClientFacingOrder.Raw[];
        total?: (number | null | undefined) | null;
        page?: (number | null | undefined) | null;
        size?: (number | null | undefined) | null;
    }
}
