// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import type * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnmatchedResult } from "./UnmatchedResult.js";

export const GetUnmatchedResultResponse: core.serialization.ObjectSchema<
    serializers.GetUnmatchedResultResponse.Raw,
    Junction.GetUnmatchedResultResponse
> = UnmatchedResult;

export declare namespace GetUnmatchedResultResponse {
    export type Raw = UnmatchedResult.Raw;
}
