// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ResultStatus } from "./ResultStatus.js";
import { UnmatchedResultTestCase } from "./UnmatchedResultTestCase.js";
import { UnmatchedResultTestFailure } from "./UnmatchedResultTestFailure.js";
import { UnmatchedResultTestOrderArtifact } from "./UnmatchedResultTestOrderArtifact.js";
import { UnmatchedResultTestOrderSource } from "./UnmatchedResultTestOrderSource.js";
import { UnmatchedResultTestRunStatus } from "./UnmatchedResultTestRunStatus.js";
import { UnmatchedResultTestStage } from "./UnmatchedResultTestStage.js";

export const GetUnmatchedResultTestResponse: core.serialization.ObjectSchema<
    serializers.GetUnmatchedResultTestResponse.Raw,
    Junction.GetUnmatchedResultTestResponse
> = core.serialization.object({
    runId: core.serialization.property("run_id", core.serialization.string()),
    status: UnmatchedResultTestRunStatus,
    stage: UnmatchedResultTestStage,
    case: UnmatchedResultTestCase,
    orderSource: core.serialization.property("order_source", UnmatchedResultTestOrderSource),
    resultStatus: core.serialization.property("result_status", ResultStatus),
    orders: core.serialization.record(core.serialization.string(), UnmatchedResultTestOrderArtifact).optional(),
    rawResultId: core.serialization.property("raw_result_id", core.serialization.string().optionalNullable()),
    error: UnmatchedResultTestFailure.optionalNullable(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    startedAt: core.serialization.property("started_at", core.serialization.date().optionalNullable()),
    completedAt: core.serialization.property("completed_at", core.serialization.date().optionalNullable()),
});

export declare namespace GetUnmatchedResultTestResponse {
    export interface Raw {
        run_id: string;
        status: UnmatchedResultTestRunStatus.Raw;
        stage: UnmatchedResultTestStage.Raw;
        case: UnmatchedResultTestCase.Raw;
        order_source: UnmatchedResultTestOrderSource.Raw;
        result_status: ResultStatus.Raw;
        orders?: Record<string, UnmatchedResultTestOrderArtifact.Raw> | null;
        raw_result_id?: (string | null | undefined) | null;
        error?: (UnmatchedResultTestFailure.Raw | null | undefined) | null;
        created_at: string;
        updated_at: string;
        started_at?: (string | null | undefined) | null;
        completed_at?: (string | null | undefined) | null;
    }
}
