// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedRespiratoryRate } from "./GroupedRespiratoryRate.js";

export const GroupedRespiratoryRateResponse: core.serialization.ObjectSchema<
    serializers.GroupedRespiratoryRateResponse.Raw,
    Junction.GroupedRespiratoryRateResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedRespiratoryRate)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedRespiratoryRateResponse {
    export interface Raw {
        groups: Record<string, GroupedRespiratoryRate.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
