// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedWorkoutSwimmingStroke } from "./GroupedWorkoutSwimmingStroke.js";

export const GroupedWorkoutSwimmingStrokeResponse: core.serialization.ObjectSchema<
    serializers.GroupedWorkoutSwimmingStrokeResponse.Raw,
    Junction.GroupedWorkoutSwimmingStrokeResponse
> = core.serialization.object({
    groups: core.serialization.record(
        core.serialization.string(),
        core.serialization.list(GroupedWorkoutSwimmingStroke),
    ),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedWorkoutSwimmingStrokeResponse {
    export interface Raw {
        groups: Record<string, GroupedWorkoutSwimmingStroke.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
