// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedVo2Max } from "./GroupedVo2Max.js";

export const GroupedVo2MaxResponse: core.serialization.ObjectSchema<
    serializers.GroupedVo2MaxResponse.Raw,
    Junction.GroupedVo2MaxResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedVo2Max)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedVo2MaxResponse {
    export interface Raw {
        groups: Record<string, GroupedVo2Max.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
