// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Select } from "./Select.js";

export const GroupKeyColumnExprGroupKey: core.serialization.Schema<
    serializers.GroupKeyColumnExprGroupKey.Raw,
    Junction.GroupKeyColumnExprGroupKey
> = core.serialization.undiscriminatedUnion([core.serialization.number(), Select]);

export declare namespace GroupKeyColumnExprGroupKey {
    export type Raw = number | Select.Raw;
}
