// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedWheelchairPush } from "./GroupedWheelchairPush.js";

export const GroupedWheelchairPushResponse: core.serialization.ObjectSchema<
    serializers.GroupedWheelchairPushResponse.Raw,
    Junction.GroupedWheelchairPushResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedWheelchairPush)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedWheelchairPushResponse {
    export interface Raw {
        groups: Record<string, GroupedWheelchairPush.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
