// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedAFibBurden } from "./GroupedAFibBurden.js";

export const GroupedAFibBurdenResponse: core.serialization.ObjectSchema<
    serializers.GroupedAFibBurdenResponse.Raw,
    Junction.GroupedAFibBurdenResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedAFibBurden)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedAFibBurdenResponse {
    export interface Raw {
        groups: Record<string, GroupedAFibBurden.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
