// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedHrv } from "./GroupedHrv.js";

export const GroupedHrvResponse: core.serialization.ObjectSchema<
    serializers.GroupedHrvResponse.Raw,
    Junction.GroupedHrvResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedHrv)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedHrvResponse {
    export interface Raw {
        groups: Record<string, GroupedHrv.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
