// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedNote } from "./GroupedNote.js";

export const GroupedNoteResponse: core.serialization.ObjectSchema<
    serializers.GroupedNoteResponse.Raw,
    Junction.GroupedNoteResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedNote)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedNoteResponse {
    export interface Raw {
        groups: Record<string, GroupedNote.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
