// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedFloorsClimbed } from "./GroupedFloorsClimbed.js";

export const GroupedFloorsClimbedResponse: core.serialization.ObjectSchema<
    serializers.GroupedFloorsClimbedResponse.Raw,
    Junction.GroupedFloorsClimbedResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedFloorsClimbed)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedFloorsClimbedResponse {
    export interface Raw {
        groups: Record<string, GroupedFloorsClimbed.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
