// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedBloodPressure } from "./GroupedBloodPressure.js";

export const GroupedBloodPressureResponse: core.serialization.ObjectSchema<
    serializers.GroupedBloodPressureResponse.Raw,
    Junction.GroupedBloodPressureResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedBloodPressure)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedBloodPressureResponse {
    export interface Raw {
        groups: Record<string, GroupedBloodPressure.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
