// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GroupedMindfulnessMinutes } from "./GroupedMindfulnessMinutes.js";

export const GroupedMindfulnessMinutesResponse: core.serialization.ObjectSchema<
    serializers.GroupedMindfulnessMinutesResponse.Raw,
    Junction.GroupedMindfulnessMinutesResponse
> = core.serialization.object({
    groups: core.serialization.record(core.serialization.string(), core.serialization.list(GroupedMindfulnessMinutes)),
    next: core.serialization.string().optionalNullable(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace GroupedMindfulnessMinutesResponse {
    export interface Raw {
        groups: Record<string, GroupedMindfulnessMinutes.Raw[]>;
        next?: (string | null | undefined) | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
