// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Address } from "./Address.js";

export const GuarantorDetails: core.serialization.ObjectSchema<
    serializers.GuarantorDetails.Raw,
    Junction.GuarantorDetails
> = core.serialization.object({
    firstName: core.serialization.property("first_name", core.serialization.string()),
    lastName: core.serialization.property("last_name", core.serialization.string()),
    address: Address,
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
    householdIncome: core.serialization.property("household_income", core.serialization.number().optionalNullable()),
    householdSize: core.serialization.property("household_size", core.serialization.number().optionalNullable()),
    email: core.serialization.string().optionalNullable(),
});

export declare namespace GuarantorDetails {
    export interface Raw {
        first_name: string;
        last_name: string;
        address: Address.Raw;
        phone_number: string;
        household_income?: (number | null | undefined) | null;
        household_size?: (number | null | undefined) | null;
        email?: (string | null | undefined) | null;
    }
}
