// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HistoricalPullTimeline: core.serialization.ObjectSchema<
    serializers.HistoricalPullTimeline.Raw,
    Junction.HistoricalPullTimeline
> = core.serialization.object({
    scheduledAt: core.serialization.property("scheduled_at", core.serialization.date()),
    startedAt: core.serialization.property("started_at", core.serialization.date().optionalNullable()),
    endedAt: core.serialization.property("ended_at", core.serialization.date().optionalNullable()),
});

export declare namespace HistoricalPullTimeline {
    export interface Raw {
        scheduled_at: string;
        started_at?: (string | null | undefined) | null;
        ended_at?: (string | null | undefined) | null;
    }
}
