// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const IndexColumnExprIndex: core.serialization.Schema<
    serializers.IndexColumnExprIndex.Raw,
    Junction.IndexColumnExprIndex
> = core.serialization.enum_([
    "sleep",
    "derived_readiness",
    "activity",
    "workout",
    "body",
    "meal",
    "menstrual_cycle",
    "profile",
    "timeseries",
]);

export declare namespace IndexColumnExprIndex {
    export type Raw =
        | "sleep"
        | "derived_readiness"
        | "activity"
        | "workout"
        | "body"
        | "meal"
        | "menstrual_cycle"
        | "profile"
        | "timeseries";
}
