// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const InsulinInjectionTimeseriesExprField: core.serialization.Schema<
    serializers.InsulinInjectionTimeseriesExprField.Raw,
    Junction.InsulinInjectionTimeseriesExprField
> = core.serialization.enum_([
    "source_provider",
    "source_type",
    "source_app_id",
    "source_workout_id",
    "source_sport",
    "timezone_offset",
    "type",
    "duration",
    "value",
    "delivery_mode",
    "delivery_form",
    "bolus_purpose",
]);

export declare namespace InsulinInjectionTimeseriesExprField {
    export type Raw =
        | "source_provider"
        | "source_type"
        | "source_app_id"
        | "source_workout_id"
        | "source_sport"
        | "timezone_offset"
        | "type"
        | "duration"
        | "value"
        | "delivery_mode"
        | "delivery_form"
        | "bolus_purpose";
}
