// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LabAccountDelegatedFlow: core.serialization.Schema<
    serializers.LabAccountDelegatedFlow.Raw,
    Junction.LabAccountDelegatedFlow
> = core.serialization.enum_(["order_delegated", "result_delegated", "fully_delegated", "not_delegated"]);

export declare namespace LabAccountDelegatedFlow {
    export type Raw = "order_delegated" | "result_delegated" | "fully_delegated" | "not_delegated";
}
