// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LabLocationMetadata: core.serialization.ObjectSchema<
    serializers.LabLocationMetadata.Raw,
    Junction.LabLocationMetadata
> = core.serialization.object({
    name: core.serialization.string(),
    state: core.serialization.string(),
    city: core.serialization.string(),
    zipCode: core.serialization.property("zip_code", core.serialization.string()),
    firstLine: core.serialization.property("first_line", core.serialization.string()),
    secondLine: core.serialization.property("second_line", core.serialization.string().optionalNullable()),
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optionalNullable()),
    faxNumber: core.serialization.property("fax_number", core.serialization.string().optionalNullable()),
    hours: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
});

export declare namespace LabLocationMetadata {
    export interface Raw {
        name: string;
        state: string;
        city: string;
        zip_code: string;
        first_line: string;
        second_line?: (string | null | undefined) | null;
        phone_number?: (string | null | undefined) | null;
        fax_number?: (string | null | undefined) | null;
        hours?: (Record<string, unknown> | null | undefined) | null;
    }
}
