// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LabReportResultSampleType: core.serialization.Schema<
    serializers.LabReportResultSampleType.Raw,
    Junction.LabReportResultSampleType
> = core.serialization.enum_(["urine", "serum_plasma_blood", "capillary_blood", "stool", "saliva", "other", "unknown"]);

export declare namespace LabReportResultSampleType {
    export type Raw = "urine" | "serum_plasma_blood" | "capillary_blood" | "stool" | "saliva" | "other" | "unknown";
}
