// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LabTestStatus } from "./LabTestStatus.js";

export const LabTestPromotion: core.serialization.ObjectSchema<
    serializers.LabTestPromotion.Raw,
    Junction.LabTestPromotion
> = core.serialization.object({
    sourceSandboxLabTestId: core.serialization.property("source_sandbox_lab_test_id", core.serialization.string()),
    productionLabTestId: core.serialization.property("production_lab_test_id", core.serialization.string()),
    status: LabTestStatus,
});

export declare namespace LabTestPromotion {
    export interface Raw {
        source_sandbox_lab_test_id: string;
        production_lab_test_id: string;
        status: LabTestStatus.Raw;
    }
}
