// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Labs } from "./Labs.js";
import { LabTestCollectionMethod } from "./LabTestCollectionMethod.js";

export const LabTestPromotionSource: core.serialization.ObjectSchema<
    serializers.LabTestPromotionSource.Raw,
    Junction.LabTestPromotionSource
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string(),
    method: LabTestCollectionMethod,
    fasting: core.serialization.boolean(),
    labSlug: core.serialization.property("lab_slug", Labs),
    providerIds: core.serialization.property("provider_ids", core.serialization.list(core.serialization.string())),
    sourceSandboxLabTestId: core.serialization.property("source_sandbox_lab_test_id", core.serialization.string()),
});

export declare namespace LabTestPromotionSource {
    export interface Raw {
        name: string;
        description: string;
        method: LabTestCollectionMethod.Raw;
        fasting: boolean;
        lab_slug: Labs.Raw;
        provider_ids: string[];
        source_sandbox_lab_test_id: string;
    }
}
