// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnmatchedResultTestCaseDefinition } from "./UnmatchedResultTestCaseDefinition.js";

export const ListUnmatchedResultTestCasesResponse: core.serialization.ObjectSchema<
    serializers.ListUnmatchedResultTestCasesResponse.Raw,
    Junction.ListUnmatchedResultTestCasesResponse
> = core.serialization.object({
    data: core.serialization.list(UnmatchedResultTestCaseDefinition),
});

export declare namespace ListUnmatchedResultTestCasesResponse {
    export interface Raw {
        data: UnmatchedResultTestCaseDefinition.Raw[];
    }
}
