// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnmatchedResultUpdate } from "./UnmatchedResultUpdate.js";

export const ListUnmatchedResultUpdatesResponse: core.serialization.ObjectSchema<
    serializers.ListUnmatchedResultUpdatesResponse.Raw,
    Junction.ListUnmatchedResultUpdatesResponse
> = core.serialization.object({
    data: core.serialization.list(UnmatchedResultUpdate).optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optionalNullable()),
});

export declare namespace ListUnmatchedResultUpdatesResponse {
    export interface Raw {
        data?: UnmatchedResultUpdate.Raw[] | null;
        next_cursor?: (string | null | undefined) | null;
    }
}
