// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SpecifiedPricingMarkerPricingConditions } from "./SpecifiedPricingMarkerPricingConditions.js";
import { UnspecifiedPricing } from "./UnspecifiedPricing.js";

export const MarkerPricingResponseDataValue: core.serialization.Schema<
    serializers.MarkerPricingResponseDataValue.Raw,
    Junction.MarkerPricingResponseDataValue
> = core.serialization.undiscriminatedUnion([SpecifiedPricingMarkerPricingConditions, UnspecifiedPricing]);

export declare namespace MarkerPricingResponseDataValue {
    export type Raw = SpecifiedPricingMarkerPricingConditions.Raw | UnspecifiedPricing.Raw;
}
