// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MatchCandidateType: core.serialization.Schema<
    serializers.MatchCandidateType.Raw,
    Junction.MatchCandidateType
> = core.serialization.enum_(["provenance_order", "order_option"]);

export declare namespace MatchCandidateType {
    export type Raw = "provenance_order" | "order_option";
}
