// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MatchReviewStatusFilter: core.serialization.Schema<
    serializers.MatchReviewStatusFilter.Raw,
    Junction.MatchReviewStatusFilter
> = core.serialization.enum_(["pending_customer_review", "pending_ops_review", "resolved"]);

export declare namespace MatchReviewStatusFilter {
    export type Raw = "pending_customer_review" | "pending_ops_review" | "resolved";
}
