// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MatchSubReasonCode: core.serialization.Schema<
    serializers.MatchSubReasonCode.Raw,
    Junction.MatchSubReasonCode
> = core.serialization.stringLiteral("lab_account_mismatch");

export declare namespace MatchSubReasonCode {
    export type Raw = "lab_account_mismatch";
}
