// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MatchCandidateConfidenceLevel } from "./MatchCandidateConfidenceLevel.js";
import { MatchCandidateReasonCode } from "./MatchCandidateReasonCode.js";
import { MatchCandidateType } from "./MatchCandidateType.js";
import { OrderLowLevelStatus } from "./OrderLowLevelStatus.js";

export const MatchReviewCandidate: core.serialization.ObjectSchema<
    serializers.MatchReviewCandidate.Raw,
    Junction.MatchReviewCandidate
> = core.serialization.object({
    candidateType: core.serialization.property("candidate_type", MatchCandidateType),
    orderId: core.serialization.property("order_id", core.serialization.string().optionalNullable()),
    orderTransactionId: core.serialization.property(
        "order_transaction_id",
        core.serialization.string().optionalNullable(),
    ),
    lastStatus: core.serialization.property("last_status", OrderLowLevelStatus.optionalNullable()),
    confidenceLevel: core.serialization.property("confidence_level", MatchCandidateConfidenceLevel),
    confidenceScore: core.serialization.property("confidence_score", core.serialization.number().optionalNullable()),
    reasons: core.serialization.list(MatchCandidateReasonCode).optional(),
    markerOverlap: core.serialization.property(
        "marker_overlap",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    ),
    statusContext: core.serialization.property(
        "status_context",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
    ),
});

export declare namespace MatchReviewCandidate {
    export interface Raw {
        candidate_type: MatchCandidateType.Raw;
        order_id?: (string | null | undefined) | null;
        order_transaction_id?: (string | null | undefined) | null;
        last_status?: (OrderLowLevelStatus.Raw | null | undefined) | null;
        confidence_level: MatchCandidateConfidenceLevel.Raw;
        confidence_score?: (number | null | undefined) | null;
        reasons?: MatchCandidateReasonCode.Raw[] | null;
        marker_overlap?: (Record<string, unknown> | null | undefined) | null;
        status_context?: (Record<string, unknown> | null | undefined) | null;
    }
}
