// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MatchCandidateReasonCode: core.serialization.Schema<
    serializers.MatchCandidateReasonCode.Raw,
    Junction.MatchCandidateReasonCode
> = core.serialization.enum_([
    "sample_id_match",
    "lab_account_mismatch",
    "matched_completed_order",
    "matched_cancelled_order",
    "invalid_collection_state",
    "demographic_mismatch",
    "demographic_match",
    "possible_wrong_lab",
    "same_lab",
    "same_user",
    "marker_overlap_exact",
    "marker_overlap_partial",
    "marker_overlap_none",
]);

export declare namespace MatchCandidateReasonCode {
    export type Raw =
        | "sample_id_match"
        | "lab_account_mismatch"
        | "matched_completed_order"
        | "matched_cancelled_order"
        | "invalid_collection_state"
        | "demographic_mismatch"
        | "demographic_match"
        | "possible_wrong_lab"
        | "same_lab"
        | "same_user"
        | "marker_overlap_exact"
        | "marker_overlap_partial"
        | "marker_overlap_none";
}
