// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McBasalBodyTemperatureFieldExprBasalBodyTemperature } from "./McBasalBodyTemperatureFieldExprBasalBodyTemperature.js";

export const McBasalBodyTemperatureFieldExpr: core.serialization.ObjectSchema<
    serializers.McBasalBodyTemperatureFieldExpr.Raw,
    Junction.McBasalBodyTemperatureFieldExpr
> = core.serialization.object({
    fieldFor: core.serialization.property("field_for", core.serialization.stringLiteral("menstrual_cycle").optional()),
    basalBodyTemperature: core.serialization.property(
        "basal_body_temperature",
        McBasalBodyTemperatureFieldExprBasalBodyTemperature,
    ),
});

export declare namespace McBasalBodyTemperatureFieldExpr {
    export interface Raw {
        field_for?: "menstrual_cycle" | null;
        basal_body_temperature: McBasalBodyTemperatureFieldExprBasalBodyTemperature.Raw;
    }
}
