// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McContraceptiveFieldExprContraceptive } from "./McContraceptiveFieldExprContraceptive.js";

export const McContraceptiveFieldExpr: core.serialization.ObjectSchema<
    serializers.McContraceptiveFieldExpr.Raw,
    Junction.McContraceptiveFieldExpr
> = core.serialization.object({
    fieldFor: core.serialization.property("field_for", core.serialization.stringLiteral("menstrual_cycle").optional()),
    contraceptive: McContraceptiveFieldExprContraceptive,
});

export declare namespace McContraceptiveFieldExpr {
    export interface Raw {
        field_for?: "menstrual_cycle" | null;
        contraceptive: McContraceptiveFieldExprContraceptive.Raw;
    }
}
