// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McHomeProgesteroneTestFieldExprHomeProgesteroneTest } from "./McHomeProgesteroneTestFieldExprHomeProgesteroneTest.js";

export const McHomeProgesteroneTestFieldExpr: core.serialization.ObjectSchema<
    serializers.McHomeProgesteroneTestFieldExpr.Raw,
    Junction.McHomeProgesteroneTestFieldExpr
> = core.serialization.object({
    fieldFor: core.serialization.property("field_for", core.serialization.stringLiteral("menstrual_cycle").optional()),
    homeProgesteroneTest: core.serialization.property(
        "home_progesterone_test",
        McHomeProgesteroneTestFieldExprHomeProgesteroneTest,
    ),
});

export declare namespace McHomeProgesteroneTestFieldExpr {
    export interface Raw {
        field_for?: "menstrual_cycle" | null;
        home_progesterone_test: McHomeProgesteroneTestFieldExprHomeProgesteroneTest.Raw;
    }
}
