// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const McHomePregnancyTestFieldExprHomePregnancyTest: core.serialization.Schema<
    serializers.McHomePregnancyTestFieldExprHomePregnancyTest.Raw,
    Junction.McHomePregnancyTestFieldExprHomePregnancyTest
> = core.serialization.enum_(["date", "test_result"]);

export declare namespace McHomePregnancyTestFieldExprHomePregnancyTest {
    export type Raw = "date" | "test_result";
}
