// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const McIntermenstrualBleedingFieldExpr: core.serialization.ObjectSchema<
    serializers.McIntermenstrualBleedingFieldExpr.Raw,
    Junction.McIntermenstrualBleedingFieldExpr
> = core.serialization.object({
    fieldFor: core.serialization.property("field_for", core.serialization.stringLiteral("menstrual_cycle").optional()),
    intermenstrualBleeding: core.serialization.property(
        "intermenstrual_bleeding",
        core.serialization.stringLiteral("date"),
    ),
});

export declare namespace McIntermenstrualBleedingFieldExpr {
    export interface Raw {
        field_for?: "menstrual_cycle" | null;
        intermenstrual_bleeding: "date";
    }
}
