// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McMenstrualFlowFieldExprMenstrualFlow } from "./McMenstrualFlowFieldExprMenstrualFlow.js";

export const McMenstrualFlowFieldExpr: core.serialization.ObjectSchema<
    serializers.McMenstrualFlowFieldExpr.Raw,
    Junction.McMenstrualFlowFieldExpr
> = core.serialization.object({
    fieldFor: core.serialization.property("field_for", core.serialization.stringLiteral("menstrual_cycle").optional()),
    menstrualFlow: core.serialization.property("menstrual_flow", McMenstrualFlowFieldExprMenstrualFlow),
});

export declare namespace McMenstrualFlowFieldExpr {
    export interface Raw {
        field_for?: "menstrual_cycle" | null;
        menstrual_flow: McMenstrualFlowFieldExprMenstrualFlow.Raw;
    }
}
