// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McSexualActivityFieldExprSexualActivity } from "./McSexualActivityFieldExprSexualActivity.js";

export const McSexualActivityFieldExpr: core.serialization.ObjectSchema<
    serializers.McSexualActivityFieldExpr.Raw,
    Junction.McSexualActivityFieldExpr
> = core.serialization.object({
    fieldFor: core.serialization.property("field_for", core.serialization.stringLiteral("menstrual_cycle").optional()),
    sexualActivity: core.serialization.property("sexual_activity", McSexualActivityFieldExprSexualActivity),
});

export declare namespace McSexualActivityFieldExpr {
    export interface Raw {
        field_for?: "menstrual_cycle" | null;
        sexual_activity: McSexualActivityFieldExprSexualActivity.Raw;
    }
}
