// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingFood } from "./ClientFacingFood.js";
import { ClientFacingSource } from "./ClientFacingSource.js";
import { Energy } from "./Energy.js";
import { Macros } from "./Macros.js";
import { Micros } from "./Micros.js";

export const MealInDbBaseClientFacingSource: core.serialization.ObjectSchema<
    serializers.MealInDbBaseClientFacingSource.Raw,
    Junction.MealInDbBaseClientFacingSource
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    priorityId: core.serialization.property("priority_id", core.serialization.number()),
    sourceId: core.serialization.property("source_id", core.serialization.number()),
    providerId: core.serialization.property("provider_id", core.serialization.string()),
    timestamp: core.serialization.date(),
    name: core.serialization.string(),
    energy: Energy.optionalNullable(),
    macros: Macros.optionalNullable(),
    micros: Micros.optionalNullable(),
    data: core.serialization.record(core.serialization.string(), ClientFacingFood).optional(),
    source: ClientFacingSource,
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    sourceAppId: core.serialization.property("source_app_id", core.serialization.string().optionalNullable()),
    sourceDeviceId: core.serialization.property("source_device_id", core.serialization.string().optionalNullable()),
});

export declare namespace MealInDbBaseClientFacingSource {
    export interface Raw {
        id: string;
        user_id: string;
        priority_id: number;
        source_id: number;
        provider_id: string;
        timestamp: string;
        name: string;
        energy?: (Energy.Raw | null | undefined) | null;
        macros?: (Macros.Raw | null | undefined) | null;
        micros?: (Micros.Raw | null | undefined) | null;
        data?: Record<string, ClientFacingFood.Raw> | null;
        source: ClientFacingSource.Raw;
        created_at: string;
        updated_at: string;
        source_app_id?: (string | null | undefined) | null;
        source_device_id?: (string | null | undefined) | null;
    }
}
