// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OrderTrackingEstimate } from "./OrderTrackingEstimate.js";

export const OrderTrackingExpectedAt: core.serialization.ObjectSchema<
    serializers.OrderTrackingExpectedAt.Raw,
    Junction.OrderTrackingExpectedAt
> = core.serialization.object({
    finalResults: core.serialization.property("final_results", OrderTrackingEstimate),
});

export declare namespace OrderTrackingExpectedAt {
    export interface Raw {
        final_results: OrderTrackingEstimate.Raw;
    }
}
