// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const OrderStatusDetail: core.serialization.Schema<
    serializers.OrderStatusDetail.Raw,
    Junction.OrderStatusDetail
> = core.serialization.enum_([
    "fulfillment_error",
    "date_of_collection_unspecified",
    "demographic_information_unspecified",
    "demographic_information_mismatch",
    "sample_quantity_not_sufficient",
    "sample_contaminated",
    "sample_stability_exceeded",
    "sample_hemolyzed",
    "sample_improper_collection",
]);

export declare namespace OrderStatusDetail {
    export type Raw =
        | "fulfillment_error"
        | "date_of_collection_unspecified"
        | "demographic_information_unspecified"
        | "demographic_information_mismatch"
        | "sample_quantity_not_sufficient"
        | "sample_contaminated"
        | "sample_stability_exceeded"
        | "sample_hemolyzed"
        | "sample_improper_collection";
}
