// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const OrderTrackingResultMarker: core.serialization.ObjectSchema<
    serializers.OrderTrackingResultMarker.Raw,
    Junction.OrderTrackingResultMarker
> = core.serialization.object({
    id: core.serialization.number().optionalNullable(),
    name: core.serialization.string(),
    slug: core.serialization.string(),
    providerId: core.serialization.property("provider_id", core.serialization.string().optionalNullable()),
});

export declare namespace OrderTrackingResultMarker {
    export interface Raw {
        id?: (number | null | undefined) | null;
        name: string;
        slug: string;
        provider_id?: (string | null | undefined) | null;
    }
}
