// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const OrderSetFastingRequirement: core.serialization.Schema<
    serializers.OrderSetFastingRequirement.Raw,
    Junction.OrderSetFastingRequirement
> = core.serialization.enum_(["fasting_not_required", "fasting_required"]);

export declare namespace OrderSetFastingRequirement {
    export type Raw = "fasting_not_required" | "fasting_required";
}
