// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OrderSetFastingRequirement } from "./OrderSetFastingRequirement.js";

export const OrderSetParameters: core.serialization.ObjectSchema<
    serializers.OrderSetParameters.Raw,
    Junction.OrderSetParameters
> = core.serialization.object({
    fasting: OrderSetFastingRequirement.optionalNullable(),
});

export declare namespace OrderSetParameters {
    export interface Raw {
        fasting?: (OrderSetFastingRequirement.Raw | null | undefined) | null;
    }
}
