// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OrderTrackingCollection } from "./OrderTrackingCollection.js";
import { OrderTrackingExpectedAt } from "./OrderTrackingExpectedAt.js";
import { OrderTrackingMarker } from "./OrderTrackingMarker.js";
import { OrderTrackingUpdate } from "./OrderTrackingUpdate.js";

export const OrderTracking: core.serialization.ObjectSchema<serializers.OrderTracking.Raw, Junction.OrderTracking> =
    core.serialization.object({
        orderId: core.serialization.property("order_id", core.serialization.string()),
        expectedAt: core.serialization.property("expected_at", OrderTrackingExpectedAt),
        collectedAt: core.serialization.property("collected_at", OrderTrackingCollection.optionalNullable()),
        markers: core.serialization.list(OrderTrackingMarker),
        updates: core.serialization.list(OrderTrackingUpdate),
    });

export declare namespace OrderTracking {
    export interface Raw {
        order_id: string;
        expected_at: OrderTrackingExpectedAt.Raw;
        collected_at?: (OrderTrackingCollection.Raw | null | undefined) | null;
        markers: OrderTrackingMarker.Raw[];
        updates: OrderTrackingUpdate.Raw[];
    }
}
