// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OrderSetPricingAggregatePricing } from "./OrderSetPricingAggregatePricing.js";
import { OrderSetPricingComponentsItem } from "./OrderSetPricingComponentsItem.js";

export const OrderSetPricing: core.serialization.ObjectSchema<
    serializers.OrderSetPricing.Raw,
    Junction.OrderSetPricing
> = core.serialization.object({
    aggregatePricing: core.serialization.property("aggregate_pricing", OrderSetPricingAggregatePricing),
    components: core.serialization.list(OrderSetPricingComponentsItem),
});

export declare namespace OrderSetPricing {
    export interface Raw {
        aggregate_pricing: OrderSetPricingAggregatePricing.Raw;
        components: OrderSetPricingComponentsItem.Raw[];
    }
}
