// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { OrderTrackingEstimate } from "./OrderTrackingEstimate.js";

export const OrderTrackingImpactedMarker: core.serialization.ObjectSchema<
    serializers.OrderTrackingImpactedMarker.Raw,
    Junction.OrderTrackingImpactedMarker
> = core.serialization.object({
    id: core.serialization.number(),
    name: core.serialization.string(),
    providerId: core.serialization.property("provider_id", core.serialization.string().optionalNullable()),
    estimates: OrderTrackingEstimate,
});

export declare namespace OrderTrackingImpactedMarker {
    export interface Raw {
        id: number;
        name: string;
        provider_id?: (string | null | undefined) | null;
        estimates: OrderTrackingEstimate.Raw;
    }
}
