// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PatchOrderCommunicationSettingsResponse: core.serialization.ObjectSchema<
    serializers.PatchOrderCommunicationSettingsResponse.Raw,
    Junction.PatchOrderCommunicationSettingsResponse
> = core.serialization.object({
    orderId: core.serialization.property("order_id", core.serialization.string()),
    smsEnabled: core.serialization.property("sms_enabled", core.serialization.boolean()),
});

export declare namespace PatchOrderCommunicationSettingsResponse {
    export interface Raw {
        order_id: string;
        sms_enabled: boolean;
    }
}
