// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PerLabCandidate: core.serialization.ObjectSchema<
    serializers.PerLabCandidate.Raw,
    Junction.PerLabCandidate
> = core.serialization.object({
    markerId: core.serialization.property("marker_id", core.serialization.number()),
    labId: core.serialization.property("lab_id", core.serialization.number()),
    labSlug: core.serialization.property("lab_slug", core.serialization.string().optionalNullable()),
    name: core.serialization.string(),
    resultNames: core.serialization.property(
        "result_names",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    providerId: core.serialization.property("provider_id", core.serialization.string().optionalNullable()),
    loincSetHash: core.serialization.property("loinc_set_hash", core.serialization.string()),
    loincCodes: core.serialization.property(
        "loinc_codes",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    loincComponents: core.serialization.property(
        "loinc_components",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    loincGroups: core.serialization.property(
        "loinc_groups",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    cptCodes: core.serialization.property("cpt_codes", core.serialization.list(core.serialization.string()).optional()),
    relation: core.serialization.string(),
    confidence: core.serialization.number(),
    reasonCodes: core.serialization.property(
        "reason_codes",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    markerPopularityScore: core.serialization.property("marker_popularity_score", core.serialization.number()),
});

export declare namespace PerLabCandidate {
    export interface Raw {
        marker_id: number;
        lab_id: number;
        lab_slug?: (string | null | undefined) | null;
        name: string;
        result_names?: string[] | null;
        provider_id?: (string | null | undefined) | null;
        loinc_set_hash: string;
        loinc_codes?: string[] | null;
        loinc_components?: string[] | null;
        loinc_groups?: string[] | null;
        cpt_codes?: string[] | null;
        relation: string;
        confidence: number;
        reason_codes?: string[] | null;
        marker_popularity_score: number;
    }
}
