// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Placeholder: core.serialization.ObjectSchema<serializers.Placeholder.Raw, Junction.Placeholder> =
    core.serialization.object({
        placeholder: core.serialization.booleanLiteral(true),
    });

export declare namespace Placeholder {
    export interface Raw {
        placeholder: true;
    }
}
