// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarkerPricingConditions } from "./MarkerPricingConditions.js";
import { PricingModifierMarkerPricingConditionsDeltaAmountMinor } from "./PricingModifierMarkerPricingConditionsDeltaAmountMinor.js";

export const PricingModifierMarkerPricingConditions: core.serialization.ObjectSchema<
    serializers.PricingModifierMarkerPricingConditions.Raw,
    Junction.PricingModifierMarkerPricingConditions
> = core.serialization.object({
    deltaAmountMinor: core.serialization.property(
        "delta_amount_minor",
        PricingModifierMarkerPricingConditionsDeltaAmountMinor,
    ),
    conditions: MarkerPricingConditions,
});

export declare namespace PricingModifierMarkerPricingConditions {
    export interface Raw {
        delta_amount_minor: PricingModifierMarkerPricingConditionsDeltaAmountMinor.Raw;
        conditions: MarkerPricingConditions.Raw;
    }
}
