// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PricingModifierRange: core.serialization.ObjectSchema<
    serializers.PricingModifierRange.Raw,
    Junction.PricingModifierRange
> = core.serialization.object({
    minimum: core.serialization.number(),
    maximum: core.serialization.number(),
});

export declare namespace PricingModifierRange {
    export interface Raw {
        minimum: number;
        maximum: number;
    }
}
