// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { QueryConfigProviderPriorityOverridesItem } from "./QueryConfigProviderPriorityOverridesItem.js";

export const QueryConfig: core.serialization.ObjectSchema<serializers.QueryConfig.Raw, Junction.QueryConfig> =
    core.serialization.object({
        providerPriorityOverrides: core.serialization.property(
            "provider_priority_overrides",
            core.serialization.list(QueryConfigProviderPriorityOverridesItem).optionalNullable(),
        ),
    });

export declare namespace QueryConfig {
    export interface Raw {
        provider_priority_overrides?: (QueryConfigProviderPriorityOverridesItem.Raw[] | null | undefined) | null;
    }
}
