// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Race: core.serialization.Schema<serializers.Race.Raw, Junction.Race> = core.serialization.enum_([
    "african_american_or_black",
    "asian",
    "indigenous_native_american_alaska_native",
    "other",
    "pacific_islander_or_hawaiian",
    "white_caucasian",
]);

export declare namespace Race {
    export type Raw =
        | "african_american_or_black"
        | "asian"
        | "indigenous_native_american_alaska_native"
        | "other"
        | "pacific_islander_or_hawaiian"
        | "white_caucasian";
}
