// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RawActivity } from "./RawActivity.js";

export const RawActivityResponse: core.serialization.ObjectSchema<
    serializers.RawActivityResponse.Raw,
    Junction.RawActivityResponse
> = core.serialization.object({
    activity: core.serialization.list(RawActivity),
});

export declare namespace RawActivityResponse {
    export interface Raw {
        activity: RawActivity.Raw[];
    }
}
