// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RawDevice } from "./RawDevice.js";

export const RawDevicesResponse: core.serialization.ObjectSchema<
    serializers.RawDevicesResponse.Raw,
    Junction.RawDevicesResponse
> = core.serialization.object({
    devices: core.serialization.list(RawDevice),
});

export declare namespace RawDevicesResponse {
    export interface Raw {
        devices: RawDevice.Raw[];
    }
}
