// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ClientFacingProvider } from "./ClientFacingProvider.js";

export const RawSleep: core.serialization.ObjectSchema<serializers.RawSleep.Raw, Junction.RawSleep> =
    core.serialization.object({
        timestamp: core.serialization.date(),
        data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        userId: core.serialization.property("user_id", core.serialization.string()),
        providerId: core.serialization.property("provider_id", core.serialization.string()),
        sourceId: core.serialization.property("source_id", core.serialization.number()),
        priorityId: core.serialization.property("priority_id", core.serialization.number().optionalNullable()),
        id: core.serialization.string(),
        sourceDeviceId: core.serialization.property("source_device_id", core.serialization.string().optionalNullable()),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
        source: ClientFacingProvider,
        priority: core.serialization.number().optionalNullable(),
    });

export declare namespace RawSleep {
    export interface Raw {
        timestamp: string;
        data: Record<string, unknown>;
        user_id: string;
        provider_id: string;
        source_id: number;
        priority_id?: (number | null | undefined) | null;
        id: string;
        source_device_id?: (string | null | undefined) | null;
        created_at?: string | null;
        updated_at?: string | null;
        source: ClientFacingProvider.Raw;
        priority?: (number | null | undefined) | null;
    }
}
