// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ReflexPricingCondition: core.serialization.ObjectSchema<
    serializers.ReflexPricingCondition.Raw,
    Junction.ReflexPricingCondition
> = core.serialization.object({});

export declare namespace ReflexPricingCondition {
    export type Raw = {};
}
