// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ResultMetadataGender: core.serialization.Schema<
    serializers.ResultMetadataGender.Raw,
    Junction.ResultMetadataGender
> = core.serialization.enum_(["male", "female", "other"]);

export declare namespace ResultMetadataGender {
    export type Raw = "male" | "female" | "other";
}
