// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AggregateFieldExpr } from "./AggregateFieldExpr.js";
import { Placeholder } from "./Placeholder.js";

export const ScalarOutputSubqueryExprSelect: core.serialization.Schema<
    serializers.ScalarOutputSubqueryExprSelect.Raw,
    Junction.ScalarOutputSubqueryExprSelect
> = core.serialization.undiscriminatedUnion([AggregateFieldExpr, Placeholder]);

export declare namespace ScalarOutputSubqueryExprSelect {
    export type Raw = AggregateFieldExpr.Raw | Placeholder.Raw;
}
