// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CanonicalCandidate } from "./CanonicalCandidate.js";
import { PerLabCandidate } from "./PerLabCandidate.js";
import { RelatedCandidate } from "./RelatedCandidate.js";
import { SearchMode } from "./SearchMode.js";

export const SearchCompendiumResponse: core.serialization.ObjectSchema<
    serializers.SearchCompendiumResponse.Raw,
    Junction.SearchCompendiumResponse
> = core.serialization.object({
    mode: SearchMode,
    selectedCanonical: core.serialization.property("selected_canonical", CanonicalCandidate.optionalNullable()),
    canonicalCandidates: core.serialization.property(
        "canonical_candidates",
        core.serialization.list(CanonicalCandidate).optional(),
    ),
    perLab: core.serialization.property(
        "per_lab",
        core.serialization.record(core.serialization.string(), core.serialization.list(PerLabCandidate)).optional(),
    ),
    related: core.serialization.list(RelatedCandidate).optional(),
});

export declare namespace SearchCompendiumResponse {
    export interface Raw {
        mode: SearchMode.Raw;
        selected_canonical?: (CanonicalCandidate.Raw | null | undefined) | null;
        canonical_candidates?: CanonicalCandidate.Raw[] | null;
        per_lab?: Record<string, PerLabCandidate.Raw[]> | null;
        related?: RelatedCandidate.Raw[] | null;
    }
}
