// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SexualActivityEntry: core.serialization.ObjectSchema<
    serializers.SexualActivityEntry.Raw,
    Junction.SexualActivityEntry
> = core.serialization.object({
    date: core.serialization.string(),
    protectionUsed: core.serialization.property("protection_used", core.serialization.boolean().optionalNullable()),
});

export declare namespace SexualActivityEntry {
    export interface Raw {
        date: string;
        protection_used?: (boolean | null | undefined) | null;
    }
}
