// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SourceType: core.serialization.Schema<serializers.SourceType.Raw, Junction.SourceType> =
    core.serialization.enum_(["app", "ble", "device", "lab", "provider"]);

export declare namespace SourceType {
    export type Raw = "app" | "ble" | "device" | "lab" | "provider";
}
