// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PricingModifierComponentPricingConditions } from "./PricingModifierComponentPricingConditions.js";

export const SpecifiedPricingComponentPricingConditions: core.serialization.ObjectSchema<
    serializers.SpecifiedPricingComponentPricingConditions.Raw,
    Junction.SpecifiedPricingComponentPricingConditions
> = core.serialization.object({
    baseAmountMinor: core.serialization.property("base_amount_minor", core.serialization.number()),
    modifiers: core.serialization.list(PricingModifierComponentPricingConditions).optionalNullable(),
});

export declare namespace SpecifiedPricingComponentPricingConditions {
    export interface Raw {
        base_amount_minor: number;
        modifiers?: (PricingModifierComponentPricingConditions.Raw[] | null | undefined) | null;
    }
}
