// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PricingModifierMarkerPricingConditions } from "./PricingModifierMarkerPricingConditions.js";

export const SpecifiedPricingMarkerPricingConditions: core.serialization.ObjectSchema<
    serializers.SpecifiedPricingMarkerPricingConditions.Raw,
    Junction.SpecifiedPricingMarkerPricingConditions
> = core.serialization.object({
    baseAmountMinor: core.serialization.property("base_amount_minor", core.serialization.number()),
    modifiers: core.serialization.list(PricingModifierMarkerPricingConditions).optionalNullable(),
});

export declare namespace SpecifiedPricingMarkerPricingConditions {
    export interface Raw {
        base_amount_minor: number;
        modifiers?: (PricingModifierMarkerPricingConditions.Raw[] | null | undefined) | null;
    }
}
