// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TimeseriesMetricPoint: core.serialization.ObjectSchema<
    serializers.TimeseriesMetricPoint.Raw,
    Junction.TimeseriesMetricPoint
> = core.serialization.object({
    date: core.serialization.date(),
    value: core.serialization.number(),
    all: core.serialization.number(),
});

export declare namespace TimeseriesMetricPoint {
    export interface Raw {
        date: string;
        value: number;
        all: number;
    }
}
