// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnmatchedResultTestOrderSource: core.serialization.Schema<
    serializers.UnmatchedResultTestOrderSource.Raw,
    Junction.UnmatchedResultTestOrderSource
> = core.serialization.enum_(["managed", "provided"]);

export declare namespace UnmatchedResultTestOrderSource {
    export type Raw = "managed" | "provided";
}
