// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnmatchedResultTestStage: core.serialization.Schema<
    serializers.UnmatchedResultTestStage.Raw,
    Junction.UnmatchedResultTestStage
> = core.serialization.enum_([
    "queued",
    "validating",
    "selecting_configuration",
    "creating_orders",
    "transitioning_orders",
    "writing_result",
    "matching_result",
    "verifying_review",
    "succeeded",
    "failed",
]);

export declare namespace UnmatchedResultTestStage {
    export type Raw =
        | "queued"
        | "validating"
        | "selecting_configuration"
        | "creating_orders"
        | "transitioning_orders"
        | "writing_result"
        | "matching_result"
        | "verifying_review"
        | "succeeded"
        | "failed";
}
