// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnmatchedResultResolutionAction: core.serialization.Schema<
    serializers.UnmatchedResultResolutionAction.Raw,
    Junction.UnmatchedResultResolutionAction
> = core.serialization.enum_(["reject", "unsure"]);

export declare namespace UnmatchedResultResolutionAction {
    export type Raw = "reject" | "unsure";
}
