// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnmatchedResultTestCase: core.serialization.Schema<
    serializers.UnmatchedResultTestCase.Raw,
    Junction.UnmatchedResultTestCase
> = core.serialization.enum_([
    "match_completed",
    "match_cancelled",
    "wrong_collection",
    "wrong_lab",
    "multiple_demo_match",
    "match_sample_id_mismatch_demo",
    "match_demo",
    "no_match",
]);

export declare namespace UnmatchedResultTestCase {
    export type Raw =
        | "match_completed"
        | "match_cancelled"
        | "wrong_collection"
        | "wrong_lab"
        | "multiple_demo_match"
        | "match_sample_id_mismatch_demo"
        | "match_demo"
        | "no_match";
}
