// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnnestExprUnnest } from "./UnnestExprUnnest.js";

export const UnnestExpr: core.serialization.ObjectSchema<serializers.UnnestExpr.Raw, Junction.UnnestExpr> =
    core.serialization.object({
        unnest: UnnestExprUnnest,
    });

export declare namespace UnnestExpr {
    export interface Raw {
        unnest: UnnestExprUnnest.Raw;
    }
}
