// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnspecifiedPricingUnspecified: core.serialization.Schema<
    serializers.UnspecifiedPricingUnspecified.Raw,
    Junction.UnspecifiedPricingUnspecified
> = core.serialization.enum_(["refer_to_contract", "price_unavailable"]);

export declare namespace UnspecifiedPricingUnspecified {
    export type Raw = "refer_to_contract" | "price_unavailable";
}
