// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnspecifiedPricingUnspecified } from "./UnspecifiedPricingUnspecified.js";

export const UnspecifiedPricing: core.serialization.ObjectSchema<
    serializers.UnspecifiedPricing.Raw,
    Junction.UnspecifiedPricing
> = core.serialization.object({
    unspecified: UnspecifiedPricingUnspecified,
});

export declare namespace UnspecifiedPricing {
    export interface Raw {
        unspecified: UnspecifiedPricingUnspecified.Raw;
    }
}
