// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Ethnicity } from "./Ethnicity.js";
import { GenderIdentity } from "./GenderIdentity.js";
import { GuarantorDetails } from "./GuarantorDetails.js";
import { Race } from "./Race.js";
import { SexualOrientation } from "./SexualOrientation.js";
import { UserAddress } from "./UserAddress.js";

export const UserInfo: core.serialization.ObjectSchema<serializers.UserInfo.Raw, Junction.UserInfo> =
    core.serialization.object({
        firstName: core.serialization.property("first_name", core.serialization.string()),
        lastName: core.serialization.property("last_name", core.serialization.string()),
        email: core.serialization.string(),
        phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
        gender: core.serialization.string(),
        dob: core.serialization.string(),
        address: UserAddress,
        medicalProxy: core.serialization.property("medical_proxy", GuarantorDetails.optionalNullable()),
        race: Race.optionalNullable(),
        ethnicity: Ethnicity.optionalNullable(),
        sexualOrientation: core.serialization.property("sexual_orientation", SexualOrientation.optionalNullable()),
        genderIdentity: core.serialization.property("gender_identity", GenderIdentity.optionalNullable()),
    });

export declare namespace UserInfo {
    export interface Raw {
        first_name: string;
        last_name: string;
        email: string;
        phone_number: string;
        gender: string;
        dob: string;
        address: UserAddress.Raw;
        medical_proxy?: (GuarantorDetails.Raw | null | undefined) | null;
        race?: (Race.Raw | null | undefined) | null;
        ethnicity?: (Ethnicity.Raw | null | undefined) | null;
        sexual_orientation?: (SexualOrientation.Raw | null | undefined) | null;
        gender_identity?: (GenderIdentity.Raw | null | undefined) | null;
    }
}
