// This file was auto-generated by Fern from our API Definition.

import * as Junction from "../../src/api/index";
import { JunctionClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("LabAccountClient", () => {
    test("get_team_lab_accounts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new JunctionClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    lab: "ayumetrix",
                    org_id: "org_id",
                    status: "active",
                    delegated_flow: "order_delegated",
                    provider_account_id: "provider_account_id",
                    account_name: "account_name",
                    default_clinical_notes: "default_clinical_notes",
                    business_units: ["business_units"],
                    allowed_billing: { key: ["AL"] },
                    team_id_allowlist: ["team_id_allowlist"],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v3/lab_test/lab_account")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.labAccount.getTeamLabAccounts({
            labAccountId: "lab_account_id",
            status: "active",
        });
        expect(response).toEqual({
            data: [
                {
                    id: "id",
                    lab: "ayumetrix",
                    orgId: "org_id",
                    status: "active",
                    delegatedFlow: "order_delegated",
                    providerAccountId: "provider_account_id",
                    accountName: "account_name",
                    defaultClinicalNotes: "default_clinical_notes",
                    businessUnits: ["business_units"],
                    allowedBilling: {
                        key: ["AL"],
                    },
                    teamIdAllowlist: ["team_id_allowlist"],
                },
            ],
        });
    });

    test("get_team_lab_accounts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new JunctionClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v3/lab_test/lab_account")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.labAccount.getTeamLabAccounts();
        }).rejects.toThrow(Junction.UnprocessableEntityError);
    });
});
