// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetPaginatedLabTestsRequestOrderDirection: core.serialization.Schema<
    serializers.GetPaginatedLabTestsRequestOrderDirection.Raw,
    Junction.GetPaginatedLabTestsRequestOrderDirection
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace GetPaginatedLabTestsRequestOrderDirection {
    export type Raw = "asc" | "desc";
}
