// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetPaginatedLabTestsRequestOrderKey: core.serialization.Schema<
    serializers.GetPaginatedLabTestsRequestOrderKey.Raw,
    Junction.GetPaginatedLabTestsRequestOrderKey
> = core.serialization.enum_(["price", "created_at", "updated_at"]);

export declare namespace GetPaginatedLabTestsRequestOrderKey {
    export type Raw = "price" | "created_at" | "updated_at";
}
