// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as Junction from "../../../index.js";

export declare namespace LinkClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class LinkClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<LinkClient.Options>;

    constructor(options: LinkClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * @param {Junction.ListBulkOpsLinkRequest} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.listBulkOps({
     *         nextCursor: "next_cursor",
     *         pageSize: 1
     *     })
     */
    public listBulkOps(
        request: Junction.ListBulkOpsLinkRequest = {},
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.BulkOpsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listBulkOps(request, requestOptions));
    }

    private async __listBulkOps(
        request: Junction.ListBulkOpsLinkRequest = {},
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.BulkOpsResponse>> {
        const { nextCursor, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            next_cursor: nextCursor,
            page_size: pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/bulk_op",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.BulkOpsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v2/link/bulk_op");
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * @param {Junction.BulkImportConnectionsBody} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.bulkImport({
     *         provider: "oura",
     *         connections: [{
     *                 userId: "user_id",
     *                 accessToken: "access_token",
     *                 refreshToken: "refresh_token",
     *                 providerId: "provider_id",
     *                 expiresAt: 1
     *             }]
     *     })
     */
    public bulkImport(
        request: Junction.BulkImportConnectionsBody,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.BulkImportConnectionsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__bulkImport(request, requestOptions));
    }

    private async __bulkImport(
        request: Junction.BulkImportConnectionsBody,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.BulkImportConnectionsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/bulk_import",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.BulkImportConnectionsBody.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.BulkImportConnectionsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v2/link/bulk_import");
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * @param {Junction.BulkTriggerHistoricalPullBody} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.bulkTriggerHistoricalPull({
     *         userIds: ["user_ids"],
     *         provider: "oura"
     *     })
     */
    public bulkTriggerHistoricalPull(
        request: Junction.BulkTriggerHistoricalPullBody,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__bulkTriggerHistoricalPull(request, requestOptions));
    }

    private async __bulkTriggerHistoricalPull(
        request: Junction.BulkTriggerHistoricalPullBody,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/bulk_trigger_historical_pull",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.BulkTriggerHistoricalPullBody.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v2/link/bulk_trigger_historical_pull",
        );
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * @param {Junction.BulkExportConnectionsBody} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.bulkExport({
     *         provider: "oura"
     *     })
     */
    public bulkExport(
        request: Junction.BulkExportConnectionsBody,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.BulkExportConnectionsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__bulkExport(request, requestOptions));
    }

    private async __bulkExport(
        request: Junction.BulkExportConnectionsBody,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.BulkExportConnectionsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/bulk_export",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.BulkExportConnectionsBody.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.BulkExportConnectionsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v2/link/bulk_export");
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * @param {Junction.BulkPauseConnectionsBody} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.bulkPause({
     *         userIds: ["user_ids"],
     *         provider: "oura"
     *     })
     */
    public bulkPause(
        request: Junction.BulkPauseConnectionsBody,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__bulkPause(request, requestOptions));
    }

    private async __bulkPause(
        request: Junction.BulkPauseConnectionsBody,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/bulk_pause",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.BulkPauseConnectionsBody.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v2/link/bulk_pause");
    }

    /**
     * Endpoint to generate a user link token, to be used throughout the vital
     * link process. The vital link token is a one time use token, that
     * expires after 10 minutes. If you would like vital-link widget to launch
     * with a specific provider, pass in a provider in the body. If you would
     * like to redirect to a custom url after successful or error connection,
     * pass in your own custom redirect_url parameter.
     *
     * @param {Junction.LinkTokenExchange} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.token({
     *         userId: "user_id"
     *     })
     */
    public token(
        request: Junction.LinkTokenExchange,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.LinkTokenExchangeResponse> {
        return core.HttpResponsePromise.fromPromise(this.__token(request, requestOptions));
    }

    private async __token(
        request: Junction.LinkTokenExchange,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.LinkTokenExchangeResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/token",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.LinkTokenExchange.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.LinkTokenExchangeResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v2/link/token");
    }

    /**
     * Generate a token to invite a user of Vital mobile app to your team
     *
     * @param {Junction.CodeCreateLinkRequest} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.codeCreate({
     *         userId: "user_id",
     *         expiresAt: new Date("2024-01-15T09:30:00.000Z")
     *     })
     */
    public codeCreate(
        request: Junction.CodeCreateLinkRequest,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.VitalTokenCreatedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__codeCreate(request, requestOptions));
    }

    private async __codeCreate(
        request: Junction.CodeCreateLinkRequest,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.VitalTokenCreatedResponse>> {
        const { userId, expiresAt } = request;
        const _queryParams: Record<string, unknown> = {
            user_id: userId,
            expires_at: expiresAt !== undefined ? expiresAt?.toISOString() : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/code/create",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.VitalTokenCreatedResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v2/link/code/create");
    }

    /**
     * This endpoint generates an OAuth link for oauth provider
     *
     * @param {Junction.GenerateOauthLinkLinkRequest} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.generateOauthLink({
     *         oauthProvider: "oura"
     *     })
     */
    public generateOauthLink(
        request: Junction.GenerateOauthLinkLinkRequest,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.Source> {
        return core.HttpResponsePromise.fromPromise(this.__generateOauthLink(request, requestOptions));
    }

    private async __generateOauthLink(
        request: Junction.GenerateOauthLinkLinkRequest,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.Source>> {
        const { oauthProvider, vitalLinkToken } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-vital-link-token": vitalLinkToken ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                `v2/link/provider/oauth/${core.url.encodePathParam(serializers.OAuthProviders.jsonOrThrow(oauthProvider))}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Source.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v2/link/provider/oauth/{oauth_provider}",
        );
    }

    /**
     * This connects auth providers that are password based.
     *
     * @param {Junction.IndividualProviderData} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.connectPasswordProvider({
     *         provider: "whoop",
     *         username: "username",
     *         password: "password"
     *     })
     */
    public connectPasswordProvider(
        request: Junction.IndividualProviderData,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.ProviderLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__connectPasswordProvider(request, requestOptions));
    }

    private async __connectPasswordProvider(
        request: Junction.IndividualProviderData,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.ProviderLinkResponse>> {
        const { provider, vitalLinkToken, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-vital-link-token": vitalLinkToken ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                `v2/link/provider/password/${core.url.encodePathParam(serializers.PasswordProviders.jsonOrThrow(provider))}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.IndividualProviderData.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ProviderLinkResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v2/link/provider/password/{provider}",
        );
    }

    /**
     * This connects auth providers that are password based.
     *
     * @param {Junction.CompletePasswordProviderMfaBody} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.completePasswordProviderMfa({
     *         provider: "whoop",
     *         mfaCode: "mfa_code"
     *     })
     */
    public completePasswordProviderMfa(
        request: Junction.CompletePasswordProviderMfaBody,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.ProviderLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__completePasswordProviderMfa(request, requestOptions));
    }

    private async __completePasswordProviderMfa(
        request: Junction.CompletePasswordProviderMfaBody,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.ProviderLinkResponse>> {
        const { provider, vitalLinkToken, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-vital-link-token": vitalLinkToken ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                `v2/link/provider/password/${core.url.encodePathParam(serializers.PasswordProviders.jsonOrThrow(provider))}/complete_mfa`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.CompletePasswordProviderMfaBody.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.ProviderLinkResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v2/link/provider/password/{provider}/complete_mfa",
        );
    }

    /**
     * This connects auth providers that are email based.
     *
     * @param {Junction.EmailProviderAuthLink} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.connectEmailAuthProvider({
     *         provider: "freestyle_libre",
     *         email: "email"
     *     })
     */
    public connectEmailAuthProvider(
        request: Junction.EmailProviderAuthLink,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__connectEmailAuthProvider(request, requestOptions));
    }

    private async __connectEmailAuthProvider(
        request: Junction.EmailProviderAuthLink,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { provider, vitalLinkToken, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-vital-link-token": vitalLinkToken ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                `v2/link/provider/email/${core.url.encodePathParam(serializers.EmailProviders.jsonOrThrow(provider))}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.EmailProviderAuthLink.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v2/link/provider/email/{provider}",
        );
    }

    /**
     * GET List of all available providers given the generated link token.
     *
     * @param {Junction.GetAllProvidersLinkRequest} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.getAllProviders()
     */
    public getAllProviders(
        request: Junction.GetAllProvidersLinkRequest = {},
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.SourceLink[]> {
        return core.HttpResponsePromise.fromPromise(this.__getAllProviders(request, requestOptions));
    }

    private async __getAllProviders(
        request: Junction.GetAllProvidersLinkRequest = {},
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.SourceLink[]>> {
        const { vitalLinkToken } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-vital-link-token": vitalLinkToken ?? undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/providers",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.link.getAllProviders.Response.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v2/link/providers");
    }

    /**
     * POST Connect the given Vital user to a demo provider.
     *
     * @param {Junction.DemoConnectionCreationPayload} request
     * @param {LinkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Junction.UnprocessableEntityError}
     *
     * @example
     *     await client.link.connectDemoProvider({
     *         userId: "user_id",
     *         provider: "apple_health_kit"
     *     })
     */
    public connectDemoProvider(
        request: Junction.DemoConnectionCreationPayload,
        requestOptions?: LinkClient.RequestOptions,
    ): core.HttpResponsePromise<Junction.DemoConnectionStatus> {
        return core.HttpResponsePromise.fromPromise(this.__connectDemoProvider(request, requestOptions));
    }

    private async __connectDemoProvider(
        request: Junction.DemoConnectionCreationPayload,
        requestOptions?: LinkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Junction.DemoConnectionStatus>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JunctionEnvironment.Production,
                "v2/link/connect/demo",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.DemoConnectionCreationPayload.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.DemoConnectionStatus.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Junction.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JunctionError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v2/link/connect/demo");
    }
}
