// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../index.js";

/**
 * @example
 *     {
 *         labAccountId: "lab_account_id",
 *         status: "active"
 *     }
 */
export interface GetTeamLabAccountsLabAccountRequest {
    labAccountId?: string | null;
    status?: Junction.LabAccountStatus | null;
}
