// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { Labs } from "../../../../types/Labs.js";
import { LabTestCollectionMethod } from "../../../../types/LabTestCollectionMethod.js";

export const CreateLabTestRequest: core.serialization.Schema<
    serializers.CreateLabTestRequest.Raw,
    Junction.CreateLabTestRequest
> = core.serialization.object({
    markerIds: core.serialization.property(
        "marker_ids",
        core.serialization.list(core.serialization.number()).optionalNullable(),
    ),
    providerIds: core.serialization.property(
        "provider_ids",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
    name: core.serialization.string(),
    method: LabTestCollectionMethod,
    description: core.serialization.string(),
    fasting: core.serialization.boolean().optionalNullable(),
    labAccountId: core.serialization.property("lab_account_id", core.serialization.string().optionalNullable()),
    labSlug: core.serialization.property("lab_slug", Labs.optionalNullable()),
});

export declare namespace CreateLabTestRequest {
    export interface Raw {
        marker_ids?: (number[] | null | undefined) | null;
        provider_ids?: (string[] | null | undefined) | null;
        name: string;
        method: LabTestCollectionMethod.Raw;
        description: string;
        fasting?: (boolean | null | undefined) | null;
        lab_account_id?: (string | null | undefined) | null;
        lab_slug?: (Labs.Raw | null | undefined) | null;
    }
}
