// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AoEAnswer } from "../../../../types/AoEAnswer.js";
import { Billing } from "../../../../types/Billing.js";
import { Consent } from "../../../../types/Consent.js";
import { HealthInsuranceCreateRequest } from "../../../../types/HealthInsuranceCreateRequest.js";
import { LabTestCollectionMethod } from "../../../../types/LabTestCollectionMethod.js";
import { OrderSetRequest } from "../../../../types/OrderSetRequest.js";
import { PatientAddressWithValidation } from "../../../../types/PatientAddressWithValidation.js";
import { PatientDetailsWithValidation } from "../../../../types/PatientDetailsWithValidation.js";
import { PhysicianCreateRequest } from "../../../../types/PhysicianCreateRequest.js";

export const CreateOrderRequestCompatible: core.serialization.Schema<
    serializers.CreateOrderRequestCompatible.Raw,
    Omit<Junction.CreateOrderRequestCompatible, "idempotencyKey" | "idempotencyError">
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.string()),
    labTestId: core.serialization.property("lab_test_id", core.serialization.string().optionalNullable()),
    orderSet: core.serialization.property("order_set", OrderSetRequest.optionalNullable()),
    collectionMethod: core.serialization.property("collection_method", LabTestCollectionMethod.optionalNullable()),
    physician: PhysicianCreateRequest.optionalNullable(),
    healthInsurance: core.serialization.property("health_insurance", HealthInsuranceCreateRequest.optionalNullable()),
    priority: core.serialization.boolean().optional(),
    billingType: core.serialization.property("billing_type", Billing.optional()),
    icdCodes: core.serialization.property(
        "icd_codes",
        core.serialization.list(core.serialization.string()).optionalNullable(),
    ),
    consents: core.serialization.list(Consent).optional(),
    activateBy: core.serialization.property("activate_by", core.serialization.string().optionalNullable()),
    aoeAnswers: core.serialization.property("aoe_answers", core.serialization.list(AoEAnswer).optionalNullable()),
    passthrough: core.serialization.string().optionalNullable(),
    clinicalNotes: core.serialization.property("clinical_notes", core.serialization.string().optionalNullable()),
    labAccountId: core.serialization.property("lab_account_id", core.serialization.string().optionalNullable()),
    creatorMemberId: core.serialization.property("creator_member_id", core.serialization.string().optionalNullable()),
    patientDetails: core.serialization.property("patient_details", PatientDetailsWithValidation),
    patientAddress: core.serialization.property("patient_address", PatientAddressWithValidation),
});

export declare namespace CreateOrderRequestCompatible {
    export interface Raw {
        user_id: string;
        lab_test_id?: (string | null | undefined) | null;
        order_set?: (OrderSetRequest.Raw | null | undefined) | null;
        collection_method?: (LabTestCollectionMethod.Raw | null | undefined) | null;
        physician?: (PhysicianCreateRequest.Raw | null | undefined) | null;
        health_insurance?: (HealthInsuranceCreateRequest.Raw | null | undefined) | null;
        priority?: boolean | null;
        billing_type?: Billing.Raw | null;
        icd_codes?: (string[] | null | undefined) | null;
        consents?: Consent.Raw[] | null;
        activate_by?: (string | null | undefined) | null;
        aoe_answers?: (AoEAnswer.Raw[] | null | undefined) | null;
        passthrough?: (string | null | undefined) | null;
        clinical_notes?: (string | null | undefined) | null;
        lab_account_id?: (string | null | undefined) | null;
        creator_member_id?: (string | null | undefined) | null;
        patient_details: PatientDetailsWithValidation.Raw;
        patient_address: PatientAddressWithValidation.Raw;
    }
}
