// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { Billing } from "../../../../types/Billing.js";
import { LabTestCollectionMethod } from "../../../../types/LabTestCollectionMethod.js";
import { OrderSetRequest } from "../../../../types/OrderSetRequest.js";

export const EstimateOrderSetPricingBody: core.serialization.Schema<
    serializers.EstimateOrderSetPricingBody.Raw,
    Junction.EstimateOrderSetPricingBody
> = core.serialization.object({
    orderSets: core.serialization.property("order_sets", core.serialization.list(OrderSetRequest)),
    modality: LabTestCollectionMethod,
    usState: core.serialization.property("us_state", core.serialization.string()),
    billing: Billing.optional(),
});

export declare namespace EstimateOrderSetPricingBody {
    export interface Raw {
        order_sets: OrderSetRequest.Raw[];
        modality: LabTestCollectionMethod.Raw;
        us_state: string;
        billing?: Billing.Raw | null;
    }
}
