// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateLabTestRequest: core.serialization.Schema<
    serializers.UpdateLabTestRequest.Raw,
    Omit<Junction.UpdateLabTestRequest, "labTestId">
> = core.serialization.object({
    name: core.serialization.string().optionalNullable(),
    active: core.serialization.boolean().optionalNullable(),
});

export declare namespace UpdateLabTestRequest {
    export interface Raw {
        name?: (string | null | undefined) | null;
        active?: (boolean | null | undefined) | null;
    }
}
