// This file was auto-generated by Fern from our API Definition.

import type * as Junction from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateOrderBody: core.serialization.Schema<
    serializers.UpdateOrderBody.Raw,
    Omit<Junction.UpdateOrderBody, "orderId">
> = core.serialization.object({
    activateBy: core.serialization.property("activate_by", core.serialization.string().optionalNullable()),
});

export declare namespace UpdateOrderBody {
    export interface Raw {
        activate_by?: (string | null | undefined) | null;
    }
}
